https://www.geeksforgeeks.org/groupby-and-filter-data-in-pyspark/

In [1]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.2.1.tar.gz (281.4 MB)
     |████████████████████████████████| 281.4 MB 33 kB/s
Collecting py4j==0.10.9.3
  Downloading py4j-0.10.9.3-py2.py3-none-any.whl (198 kB)
     |████████████████████████████████| 198 kB 45.6 MB/s
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.2.1-py2.py3-none-any.whl size=281853642 sha256=2280c0aa14b808b355591ebc7a38e469cf56c7941d7145acd8b0d46f2147339c
  Stored in directory: /root/.cache/pip/wheels/9f/f5/07/7cd8017084dce4e93e84e92efd1e1d5334db05f2e83bcef74f
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.9.3 pyspark-3.2.1

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

import pandas as pd
from pyspark.sql import Row

df = spark.createDataFrame([
    Row(acct_holder_customer_nbr=90),
    Row(acct_holder_customer_nbr=45),
    Row(acct_holder_customer_nbr=67),
    Row(acct_holder_customer_nbr=2),
    Row(acct_holder_customer_nbr=32),
    Row(acct_holder_customer_nbr=12),
    Row(acct_holder_customer_nbr=11)
])
df

DataFrame[acct_holder_customer_nbr: bigint]

In [ ]:
df.show()

+------------------------+
|acct_holder_customer_nbr|
+------------------------+
|                      90|
|                      45|
|                      67|
|                       2|
|                      32|
|                      12|
|                      11|
+------------------------+

In [ ]:
#df.createOrReplaceTempView("suppnodupkey")

In [ ]:
#spark.sql("SELECT * from suppnodupkey order by acct_holder_customer_nbr asc").show()

df.orderBy("acct_holder_customer_nbr").show(truncate=False)

+------------------------+
|acct_holder_customer_nbr|
+------------------------+
|2                       |
|11                      |
|12                      |
|32                      |
|45                      |
|67                      |
|90                      |
+------------------------+

- input:
- PROC SORT data=work.gsabiacacc ;
- by var001 var002 dtjour numcomsi ;
- run ;



- output:
- import findspark
- def PROC_SORT(data,sort_key):
	  data =data.orderBy(cols, ascending=True)
	  return data
- gsabiacacc = spark.createDataFrame(gsabiacacc)
- gsabiacacc = PROC_SORT(data=gsabiacacc, sort_key=['var001', 'var002','dtjour','numcomsi'])
- gsabiacacc

In [ ]:
simpleData = [("James","Sales","NY",90000,34,10000), \
    ("Michael","Sales","NY",86000,56,20000), \
    ("Robert","Sales","CA",81000,30,23000), \
    ("Maria","Finance","CA",90000,24,23000), \
    ("Raman","Finance","CA",99000,40,24000), \
    ("Scott","Finance","NY",83000,36,19000), \
    ("Jen","Finance","NY",79000,53,15000), \
    ("Jeff","Marketing","CA",80000,25,18000), \
    ("Kumar","Marketing","NY",91000,50,21000) \
  ]

In [ ]:
simpleData

[('James', 'Sales', 'NY', 90000, 34, 10000),
 ('Michael', 'Sales', 'NY', 86000, 56, 20000),
 ('Robert', 'Sales', 'CA', 81000, 30, 23000),
 ('Maria', 'Finance', 'CA', 90000, 24, 23000),
 ('Raman', 'Finance', 'CA', 99000, 40, 24000),
 ('Scott', 'Finance', 'NY', 83000, 36, 19000),
 ('Jen', 'Finance', 'NY', 79000, 53, 15000),
 ('Jeff', 'Marketing', 'CA', 80000, 25, 18000),
 ('Kumar', 'Marketing', 'NY', 91000, 50, 21000)]

In [ ]:
columns= ["employee_name","department","state","salary","age","bonus"]
df = spark.createDataFrame(data = simpleData, schema = columns)
df.printSchema()
df.show(truncate=False)

root
 |-- employee_name: string (nullable = true)
 |-- department: string (nullable = true)
 |-- state: string (nullable = true)
 |-- salary: long (nullable = true)
 |-- age: long (nullable = true)
 |-- bonus: long (nullable = true)

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|James        |Sales     |NY   |90000 |34 |10000|
|Michael      |Sales     |NY   |86000 |56 |20000|
|Robert       |Sales     |CA   |81000 |30 |23000|
|Maria        |Finance   |CA   |90000 |24 |23000|
|Raman        |Finance   |CA   |99000 |40 |24000|
|Scott        |Finance   |NY   |83000 |36 |19000|
|Jen          |Finance   |NY   |79000 |53 |15000|
|Jeff         |Marketing |CA   |80000 |25 |18000|
|Kumar        |Marketing |NY   |91000 |50 |21000|
+-------------+----------+-----+------+---+-----+

In [ ]:
# DataFrame sorting using the sort() function
# PySpark DataFrame class provides sort() function to sort on one or more columns. By default, it sorts by ascending order.

df.sort("department","state").show(truncate=False)

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|Raman        |Finance   |CA   |99000 |40 |24000|
|Maria        |Finance   |CA   |90000 |24 |23000|
|Scott        |Finance   |NY   |83000 |36 |19000|
|Jen          |Finance   |NY   |79000 |53 |15000|
|Jeff         |Marketing |CA   |80000 |25 |18000|
|Kumar        |Marketing |NY   |91000 |50 |21000|
|Robert       |Sales     |CA   |81000 |30 |23000|
|James        |Sales     |NY   |90000 |34 |10000|
|Michael      |Sales     |NY   |86000 |56 |20000|
+-------------+----------+-----+------+---+-----+

In [ ]:
# DataFrame sorting using orderBy() function
# PySpark DataFrame also provides orderBy() function to sort on one or more columns. By default, it orders by ascending.

df.orderBy("department","state").show(truncate=False)

+-------------+----------+-----+------+---+-----+
|employee_name|department|state|salary|age|bonus|
+-------------+----------+-----+------+---+-----+
|Raman        |Finance   |CA   |99000 |40 |24000|
|Maria        |Finance   |CA   |90000 |24 |23000|
|Scott        |Finance   |NY   |83000 |36 |19000|
|Jen          |Finance   |NY   |79000 |53 |15000|
|Jeff         |Marketing |CA   |80000 |25 |18000|
|Kumar        |Marketing |NY   |91000 |50 |21000|
|Robert       |Sales     |CA   |81000 |30 |23000|
|James        |Sales     |NY   |90000 |34 |10000|
|Michael      |Sales     |NY   |86000 |56 |20000|
+-------------+----------+-----+------+---+-----+

proc sql;
create table FINAL_ELIGIBLE_BASE_&mmmyy._1 as
select *
from FINAL_ELIGIBLE_BASE_&mmmyy._1
where document_nbr not in (select distinct document_nbr from bs.FINAL_CONTROL_BASE);
quit;

In [ ]:
import pyspark
from pyspark.sql import SQLContext
sc = pyspark.SparkContext()
sqlCtx = SQLContext(sc)
from pyspark import SparkConf, SparkContext, conf
sc = SparkContext.getOrCreate(conf=conf)
sqlCtx.sql("create table FINAL_ELIGIBLE_BASE_&mmmyy._1 as
select *
from FINAL_ELIGIBLE_BASE_&mmmyy._1
where document_nbr not in (select distinct document_nbr from bs.FINAL_CONTROL_BASE")

p26

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

import pandas as pd
from pyspark.sql import Row

df = spark.createDataFrame([
    Row(loan_source=1, cust_group=2, channel=3),
    Row(loan_source=4, cust_group=5, channel=6),
    Row(loan_source=7, cust_group=8, channel=9)
])
df

DataFrame[loan_source: bigint, cust_group: bigint, channel: bigint]

In [ ]:
df.show()

+-----------+----------+-------+
|loan_source|cust_group|channel|
+-----------+----------+-------+
|          1|         2|      3|
|          4|         5|      6|
|          7|         8|      9|
+-----------+----------+-------+

In [ ]:
type(df)

pyspark.sql.dataframe.DataFrame

In [ ]:
from pyspark.sql import functions as F
result = df.groupBy('loan_source').agg(
    F.count('loan_source').alias('Frequency')
).selectExpr(
    '*',
    '100 * Frequency / sum(Frequency) over() Percent'
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    'sum(Percent) over(order by Frequency desc) Cumulative_Percent'
)

result.show()

+-----------+---------+------------------+--------------------+------------------+
|loan_source|Frequency|           Percent|Cumulative_Frequency|Cumulative_Percent|
+-----------+---------+------------------+--------------------+------------------+
|          1|        1|33.333333333333336|                   3|             100.0|
|          7|        1|33.333333333333336|                   3|             100.0|
|          4|        1|33.333333333333336|                   3|             100.0|
+-----------+---------+------------------+--------------------+------------------+

In [ ]:
result1 = df.groupBy('cust_group').agg(
    F.count('cust_group').alias('Frequency')
).selectExpr(
    '*',
    '100 * Frequency / sum(Frequency) over() Percent'
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    'sum(Percent) over(order by Frequency desc) Cumulative_Percent'
)

result1.show()

+----------+---------+------------------+--------------------+------------------+
|cust_group|Frequency|           Percent|Cumulative_Frequency|Cumulative_Percent|
+----------+---------+------------------+--------------------+------------------+
|         2|        1|33.333333333333336|                   3|             100.0|
|         5|        1|33.333333333333336|                   3|             100.0|
|         8|        1|33.333333333333336|                   3|             100.0|
+----------+---------+------------------+--------------------+------------------+

In [ ]:
result2 = df.groupBy('cust_group').agg(
    F.count('cust_group').alias('Frequency')
).selectExpr(
    '*',
    '100 * Frequency / sum(Frequency) over() Percent'
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    'sum(Percent) over(order by Frequency desc) Cumulative_Percent'
)

result2.show()

p193

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()

import pandas as pd
from pyspark.sql import Row

df = spark.createDataFrame([
    Row(exceed35X_excl=23, total_oti=45),
    Row(exceed35X_excl=34, total_oti=67),
    Row(exceed35X_excl=21, total_oti=78),
    Row(exceed35X_excl=45, total_oti=65),
    Row(exceed35X_excl=45, total_oti=90)
    ])
df

DataFrame[exceed35X_excl: bigint, total_oti: bigint]

In [ ]:
df.show()

+--------------+---------+
|exceed35X_excl|total_oti|
+--------------+---------+
|            23|       45|
|            34|       67|
|            21|       78|
|            45|       65|
|            45|       90|
+--------------+---------+

In [ ]:
df.createOrReplaceTempView("base1c")

In [ ]:
result = spark.sql("select distinct exceed35X_excl, max(total_oti) as max_oti, min(total_oti) as min_oti from base1c group by exceed35X_excl")

result.show()

+--------------+-------+-------+
|exceed35X_excl|max_oti|min_oti|
+--------------+-------+-------+
|            34|     67|     67|
|            23|     45|     45|
|            21|     78|     78|
|            45|     90|     65|
+--------------+-------+-------+

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()

import pandas as pd
from pyspark.sql import Row

df = spark.createDataFrame([
    Row(exceed35X_excl=23, total_oti=45),
    Row(exceed35X_excl=34, total_oti=67),
    Row(exceed35X_excl=21, total_oti=78),
    Row(exceed35X_excl=45, total_oti=65),
    Row(exceed35X_excl=45, total_oti=90)
    ])

df.createOrReplaceTempView("base1c")
result = spark.sql("select distinct exceed35X_excl, max(total_oti) as max_oti, min(total_oti) as min_oti from base1c group by exceed35X_excl")

result.show()

p344

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()

data=([3,2,3],[1,1,2],[1,3,4],[1,2,1],[2,2,2],[3,2,1],[1,1,1])
columns=['document_nbr','col1','col2']
bs_FINAL_ELIGIBLE_BASE_mmmyy_1= spark.createDataFrame(data=data,schema=columns)
bs_FINAL_ELIGIBLE_BASE_mmmyy_1.show()

bs_FINAL_ELIGIBLE_BASE_mmmyy_1.createOrReplaceTempView("bs_FINAL_ELIGIBLE_BASE_mmmyy_1")

In [ ]:
data=([3,2,3],[1,1,2],[1,3,4],[1,2,1],[2,2,2],[3,2,1],[1,1,1])
columns=['document_nbr','col1','col2']
bs_FINAL_ELIGIBLE_BASE_mmmyy_1= spark.createDataFrame(data=data,schema=columns)
bs_FINAL_ELIGIBLE_BASE_mmmyy_1.show()

+------------+----+----+
|document_nbr|col1|col2|
+------------+----+----+
|           3|   2|   3|
|           1|   1|   2|
|           1|   3|   4|
|           1|   2|   1|
|           2|   2|   2|
|           3|   2|   1|
|           1|   1|   1|
+------------+----+----+

In [ ]:
bs_FINAL_ELIGIBLE_BASE_mmmyy_1.createOrReplaceTempView("bs_FINAL_ELIGIBLE_BASE_mmmyy_1")

In [ ]:
chk=spark.sql("""

select document_nbr, count(*) as cnt

from bs_FINAL_ELIGIBLE_BASE_mmmyy_1

group by document_nbr having cnt > 1

""")

In [ ]:
chk.show()

+------------+---+
|document_nbr|cnt|
+------------+---+
|           1|  4|
|           3|  2|
+------------+---+

p76

data card_base1;
input income_update_36 income_update;
datalines;
1200 1234
1308 1320
2009 2020
1298 1300
2356 2300
1200 1500
;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=([1200, 1234],[1308, 1320],[2009, 2020],[1298, 1300],[2356, 2300],[1200, 1500])
columns=['income_update_36','income_update']
card_base1 = spark.createDataFrame(data=data,schema=columns)
card_base1.show()

+----------------+-------------+
|income_update_36|income_update|
+----------------+-------------+
|            1200|         1234|
|            1308|         1320|
|            2009|         2020|
|            1298|         1300|
|            2356|         2300|
|            1200|         1500|
+----------------+-------------+

In [ ]:
card_base1.createOrReplaceTempView("card_base1")

In [ ]:
#import org.apache.spark.sql.functions._
from pyspark.sql.types import StringType
result = spark.sql("""

select distinct income_update_36, min(income_update) as min_update  , max(income_update) as max_update , count(*) from card_base1 group by income_update_36

""")
result.show()

+----------------+----------+----------+--------+
|income_update_36|min_update|max_update|count(1)|
+----------------+----------+----------+--------+
|            1200|      1234|      1500|       2|
|            2009|      2020|      2020|       1|
|            1308|      1320|      1320|       1|
|            2356|      2300|      2300|       1|
|            1298|      1300|      1300|       1|
+----------------+----------+----------+--------+

p281

- data FINAL_PREAPPROVE_MEMO_BASE_mmmyy;
- input pre_pil pre_csh cms_grade fail_dsr age;
- datalines;
- 1 2 3 4 5
- 4 5 6 7 8
- 9 3 5 6 8
- 1 2 3 4 6
- ;
- run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=([1, 2, 3, 4, 5],[4, 5, 6, 7, 8],[9, 3, 5, 6, 8],[1,2,3,4,6])
columns=['pre_pil','pre_csh', 'cms_grade', 'fail_dsr', 'age']
FINAL_PREAPPROVE_MEMO_BASE_mmmyy = spark.createDataFrame(data=data,schema=columns)
FINAL_PREAPPROVE_MEMO_BASE_mmmyy.show()
#FINAL_PREAPPROVE_MEMO_BASE_mmmyy.createOrReplaceTempView("FINAL_PREAPPROVE_MEMO_BASE_mmmyy")

+-------+-------+---------+--------+---+
|pre_pil|pre_csh|cms_grade|fail_dsr|age|
+-------+-------+---------+--------+---+
|      1|      2|        3|       4|  5|
|      4|      5|        6|       7|  8|
|      9|      3|        5|       6|  8|
|      1|      2|        3|       4|  6|
+-------+-------+---------+--------+---+

- proc freq data = FINAL_PREAPPROVE_MEMO_BASE_mmmyy;
- table pre_pil pre_csh cms_grade fail_dsr age / norow nocol nopercent;
- run;

In [ ]:
from pyspark.sql import functions as F
result = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('pre_pil').agg(
    F.count('pre_pil').alias('Frequency')
).selectExpr(
    '*',
    '100 * Frequency / sum(Frequency) over() Percent'
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    'sum(Percent) over(order by Frequency desc) Cumulative_Percent'
)

result.show()

+-------+---------+-------+--------------------+------------------+
|pre_pil|Frequency|Percent|Cumulative_Frequency|Cumulative_Percent|
+-------+---------+-------+--------------------+------------------+
|      1|        2|   50.0|                   2|              50.0|
|      4|        1|   25.0|                   4|             100.0|
|      9|        1|   25.0|                   4|             100.0|
+-------+---------+-------+--------------------+------------------+

In [ ]:
from pyspark.sql import functions as F
result = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('pre_pil').agg(
    F.count('pre_pil').alias('Frequency')
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    
)

result.show()

result1 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('pre_csh').agg(
    F.count('pre_csh').alias('Frequency')
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    
)

result1.show()

result2 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('cms_grade').agg(
    F.count('cms_grade').alias('Frequency')
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    
)

result2.show()

result3 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('fail_dsr').agg(
    F.count('fail_dsr').alias('Frequency')
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    
)

result3.show()

result4 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('age').agg(
    F.count('age').alias('Frequency')
).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency', 
    
)

result4.show()

+-------+---------+--------------------+
|pre_pil|Frequency|Cumulative_Frequency|
+-------+---------+--------------------+
|      1|        2|                   2|
|      4|        1|                   4|
|      9|        1|                   4|
+-------+---------+--------------------+

+-------+---------+--------------------+
|pre_csh|Frequency|Cumulative_Frequency|
+-------+---------+--------------------+
|      2|        2|                   2|
|      5|        1|                   4|
|      3|        1|                   4|
+-------+---------+--------------------+

+---------+---------+--------------------+
|cms_grade|Frequency|Cumulative_Frequency|
+---------+---------+--------------------+
|        3|        2|                   2|
|        6|        1|                   4|
|        5|        1|                   4|
+---------+---------+--------------------+

+--------+---------+--------------------+
|fail_dsr|Frequency|Cumulative_Frequency|
+--------+---------+--------------------+
|       4|        2|                   2|
|       7|        1|                   4|
|       6|        1|                   4|
+--------+---------+--------------------+

+---+---------+--------------------+
|age|Frequency|Cumulative_Frequency|
+---+---------+--------------------+
|  8|        2|                   2|
|  5|        1|                   4|
|  6|        1|                   4|
+---+---------+--------------------+

In [ ]:
from pyspark.sql import functions as F

result = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('pre_pil').agg(F.count('pre_pil').alias('Frequency'))
final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
final_res.show()

result1 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('pre_csh').agg(F.count('pre_csh').alias('Frequency'))
final_res1 = result1.withColumn('Cumulative_Frequency', F.sum(result1.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
final_res1.show()

result2 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('cms_grade').agg(F.count('cms_grade').alias('Frequency'))
final_res2 = result2.withColumn('Cumulative_Frequency', F.sum(result2.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
final_res2.show()

result3 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('fail_dsr').agg(F.count('fail_dsr').alias('Frequency'))
final_res3 = result3.withColumn('Cumulative_Frequency', F.sum(result3.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
final_res3.show()

result4 = FINAL_PREAPPROVE_MEMO_BASE_mmmyy.groupBy('age').agg(F.count('age').alias('Frequency'))
final_res4 = result4.withColumn('Cumulative_Frequency', F.sum(result4.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
final_res4.show()

+-------+---------+--------------------+
|pre_pil|Frequency|Cumulative_Frequency|
+-------+---------+--------------------+
|      1|        2|                   2|
|      4|        1|                   3|
|      9|        1|                   4|
+-------+---------+--------------------+

+-------+---------+--------------------+
|pre_csh|Frequency|Cumulative_Frequency|
+-------+---------+--------------------+
|      5|        1|                   1|
|      2|        2|                   3|
|      3|        1|                   4|
+-------+---------+--------------------+

+---------+---------+--------------------+
|cms_grade|Frequency|Cumulative_Frequency|
+---------+---------+--------------------+
|        6|        1|                   1|
|        3|        2|                   3|
|        5|        1|                   4|
+---------+---------+--------------------+

+--------+---------+--------------------+
|fail_dsr|Frequency|Cumulative_Frequency|
+--------+---------+--------------------+
|       7|        1|                   1|
|       4|        2|                   3|
|       6|        1|                   4|
+--------+---------+--------------------+

+---+---------+--------------------+
|age|Frequency|Cumulative_Frequency|
+---+---------+--------------------+
|  5|        1|                   1|
|  8|        2|                   3|
|  6|        1|                   4|
+---+---------+--------------------+

In [ ]:
def proc_freq(data):

  result = data.groupBy('pre_pil').agg(F.count('pre_pil').alias('Frequency'))
  final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  result1 = data.groupBy('pre_csh').agg(F.count('pre_csh').alias('Frequency'))
  final_res1 = result1.withColumn('Cumulative_Frequency', F.sum(result1.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))


  result2 = data.groupBy('cms_grade').agg(F.count('cms_grade').alias('Frequency'))
  final_res2 = result2.withColumn('Cumulative_Frequency', F.sum(result2.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
  

  result3 = data.groupBy('fail_dsr').agg(F.count('fail_dsr').alias('Frequency'))
  final_res3 = result3.withColumn('Cumulative_Frequency', F.sum(result3.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))


  result4 = data.groupBy('age').agg(F.count('age').alias('Frequency'))
  final_res4 = result4.withColumn('Cumulative_Frequency', F.sum(result4.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  return final_res, final_res1, final_res2, final_res3, final_res4

In [ ]:
def proc_freq(data):

  result = data.groupBy('pre_pil').agg(F.count('pre_pil').alias('Frequency'))
  final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  result1 = data.groupBy('pre_csh').agg(F.count('pre_csh').alias('Frequency'))
  final_res1 = result1.withColumn('Cumulative_Frequency', F.sum(result1.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))


  result2 = data.groupBy('cms_grade').agg(F.count('cms_grade').alias('Frequency'))
  final_res2 = result2.withColumn('Cumulative_Frequency', F.sum(result2.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
  

  result3 = data.groupBy('fail_dsr').agg(F.count('fail_dsr').alias('Frequency'))
  final_res3 = result3.withColumn('Cumulative_Frequency', F.sum(result3.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))


  result4 = data.groupBy('age').agg(F.count('age').alias('Frequency'))
  final_res4 = result4.withColumn('Cumulative_Frequency', F.sum(result4.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  return final_res, final_res1, final_res2, final_res3, final_res4



pre_pil, pre_csh, cms_grade, fail_dsr, age = proc_freq(data = FINAL_PREAPPROVE_MEMO_BASE_mmmyy)
pre_pil.show()
pre_csh.show()
cms_grade.show()
fail_dsr.show()
age.show()

+-------+---------+--------------------+
|pre_pil|Frequency|Cumulative_Frequency|
+-------+---------+--------------------+
|      1|        2|                   2|
|      4|        1|                   3|
|      9|        1|                   4|
+-------+---------+--------------------+

+-------+---------+--------------------+
|pre_csh|Frequency|Cumulative_Frequency|
+-------+---------+--------------------+
|      5|        1|                   1|
|      2|        2|                   3|
|      3|        1|                   4|
+-------+---------+--------------------+

+---------+---------+--------------------+
|cms_grade|Frequency|Cumulative_Frequency|
+---------+---------+--------------------+
|        6|        1|                   1|
|        3|        2|                   3|
|        5|        1|                   4|
+---------+---------+--------------------+

+--------+---------+--------------------+
|fail_dsr|Frequency|Cumulative_Frequency|
+--------+---------+--------------------+
|       7|        1|                   1|
|       4|        2|                   3|
|       6|        1|                   4|
+--------+---------+--------------------+

+---+---------+--------------------+
|age|Frequency|Cumulative_Frequency|
+---+---------+--------------------+
|  5|        1|                   1|
|  8|        2|                   3|
|  6|        1|                   4|
+---+---------+--------------------+

p302

- data ul_appl;
- input document_nbr appl_type appl_number;
- datalines;
- 1 2 3
- 4 5 6
- 7 8 9
- ;
- run;

- data ul_aaps;
- input document_nbr appl_type appl_nbr;
- datalines;
- 11 2 3
- 41 53 6
- 73 8 9
- ;
- run;



- proc sql;
	*create table temp as;
	select distinct  a.*
				,c.document_nbr  as document_number
	from ul_appl as a
	left join ul_aaps as c
	on a.appl_type=c.appl_type             
	and a.appl_number=c.appl_nbr;
- quit;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=([1, 2, 3],[4, 5, 6],[7,8,9])
columns=['document_nbr', 'appl_type', 'appl_number']  
ul_appl = spark.createDataFrame(data=data,schema=columns)
ul_appl.show()
ul_appl.createOrReplaceTempView("ul_appl")

+------------+---------+-----------+
|document_nbr|appl_type|appl_number|
+------------+---------+-----------+
|           1|        2|          3|
|           4|        5|          6|
|           7|        8|          9|
+------------+---------+-----------+

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=([11, 2, 3],[41, 53, 6],[73, 8, 9])
columns=['document_nbr', 'appl_type', 'appl_nbr']
ul_aaps = spark.createDataFrame(data=data,schema=columns)     
ul_aaps.show()
ul_aaps.createOrReplaceTempView("ul_aaps")

+------------+---------+--------+
|document_nbr|appl_type|appl_nbr|
+------------+---------+--------+
|          11|        2|       3|
|          41|       53|       6|
|          73|        8|       9|
+------------+---------+--------+

In [ ]:
result = spark.sql("""
	
	select distinct  a.*
				,c.document_nbr  as document_number
	from ul_appl as a
	LEFT JOIN ul_aaps as c
	on a.appl_type=c.appl_type             
	and a.appl_number=c.appl_nbr

""")

result.show()

+------------+---------+-----------+---------------+
|document_nbr|appl_type|appl_number|document_number|
+------------+---------+-----------+---------------+
|           1|        2|          3|             11|
|           4|        5|          6|           null|
|           7|        8|          9|             73|
+------------+---------+-----------+---------------+

p323

- data campaign_base1;
- input group1 fi_flag expo_annual_income exist_dsr total_oti;
- datalines;
- 12 14 87000 10
- 23 45 67000 11
- 12 47 160000 8
- 32 43 140000 10
- 23 19 134000 9
- 32 56 90000  7
- ;
- run;

- proc sql;
- select distinct group1, fi_flag,
- min(expo_annual_income) as min_income, max(expo_annual_income) as max_income, 
min( exist_dsr) as  min_dsr, max( exist_dsr) as  max_dsr, 
count(*) from campaign_base1
where total_oti<12 and expo_annual_income<150000
group by group1,fi_flag;
quit;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=([12, 14, 87000, 10, 11],[23, 45, 67000, 11, 8],[12, 47, 160000, 8, 10], 
      [32, 43, 140000, 10, 9],[23, 19, 134000, 9, 11], [32, 56, 90000, 7,6])
columns=['group1', 'fi_flag', 'expo_annual_income', 'exist_dsr', 'total_oti']
campaign_base1 = spark.createDataFrame(data=data,schema=columns)
campaign_base1.show()
campaign_base1.createOrReplaceTempView("campaign_base1")

+------+-------+------------------+---------+---------+
|group1|fi_flag|expo_annual_income|exist_dsr|total_oti|
+------+-------+------------------+---------+---------+
|    12|     14|             87000|       10|       11|
|    23|     45|             67000|       11|        8|
|    12|     47|            160000|        8|       10|
|    32|     43|            140000|       10|        9|
|    23|     19|            134000|        9|       11|
|    32|     56|             90000|        7|        6|
+------+-------+------------------+---------+---------+

In [ ]:
result = spark.sql("""

select distinct group1,fi_flag,
min(expo_annual_income) as min_income, max(expo_annual_income) as max_income, min( exist_dsr) as  min_dsr, max( exist_dsr) as  max_dsr, 
count(*) from campaign_base1
WHERE total_oti<12 and expo_annual_income<150000
group by group1,fi_flag

""")

result.show()

+------+-------+----------+----------+-------+-------+--------+
|group1|fi_flag|min_income|max_income|min_dsr|max_dsr|count(1)|
+------+-------+----------+----------+-------+-------+--------+
|    12|     14|     87000|     87000|     10|     10|       1|
|    23|     45|     67000|     67000|     11|     11|       1|
|    23|     19|    134000|    134000|      9|      9|       1|
|    32|     56|     90000|     90000|      7|      7|       1|
|    32|     43|    140000|    140000|     10|     10|       1|
+------+-------+----------+----------+-------+-------+--------+

p442;

- data last_market_date;
- input as_of_date year month;
- datalines;
- 14062020 2020 06
- 12042021 2021 04
- 13042021 2021 04
- 15092021 2021 09
- 18072021 2021 07
- 05022022 2022 02
- 13012022 2022 01
- ;
- run;


- proc sql;
-  create table last_market_date as;
- select max(as_of_date)as last_market_date format date9. 
	   ,year
	   ,month 
from last_market_date
group by year, month;
- quit;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=([14062020, 2020, 6],[12042021, 2021, 4],[13042021, 2021, 4], 
      [15092021, 2021, 9],[18072021, 2021, 7], [5022022, 2022, 2], [13012022, 2022, 1])
columns=['as_of_date', 'year', 'month']
last_market_date = spark.createDataFrame(data=data,schema=columns)
last_market_date.show()
last_market_date.createOrReplaceTempView("last_market_date")

+----------+----+-----+
|as_of_date|year|month|
+----------+----+-----+
|  14062020|2020|    6|
|  12042021|2021|    4|
|  13042021|2021|    4|
|  15092021|2021|    9|
|  18072021|2021|    7|
|   5022022|2022|    2|
|  13012022|2022|    1|
+----------+----+-----+

In [ ]:
result = spark.sql("""

select max(as_of_date)as last_market_date  
	   ,year
	   ,month 
from last_market_date
group by year, month

""")

result.show()

+----------------+----+-----+
|last_market_date|year|month|
+----------------+----+-----+
|        14062020|2020|    6|
|        13042021|2021|    4|
|        13012022|2022|    1|
|        18072021|2021|    7|
|        15092021|2021|    9|
|         5022022|2022|    2|
+----------------+----+-----+


p280

- data tbase4;
- input failtype no_pa_amt;
- datalines;
- 12 1
- 76 98
- 14 1
- 15 78
- ;
- run;

- proc freq data = tbase4;
- table failtype/missing nocol norow nopct;
- where no_pa_amt = 1;
- run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()
data=[[12,1],[76,98], [14,1], [15, 78], [13,1], [15,1]]
columns=['failtype', 'no_pa_amt']
tbase4 = spark.createDataFrame(data=data,schema=columns)
tbase4.show()
#tbase4.createOrReplaceTempView("tbase4")

+--------+---------+
|failtype|no_pa_amt|
+--------+---------+
|      12|        1|
|      76|       98|
|      14|        1|
|      15|       78|
|      13|        1|
|      15|        1|
+--------+---------+

In [ ]:
#from pyspark.sql import functions as F
from pyspark.sql.functions import col, count

tbase4 = tbase4.filter(tbase4.no_pa_amt == 1)
result = tbase4.groupBy('failtype').agg(
    count('failtype').alias('Frequency')).selectExpr(
    '*',
    'sum(Frequency) over(order by Frequency desc) Cumulative_Frequency')

result.show()

+--------+---------+--------------------+
|failtype|Frequency|Cumulative_Frequency|
+--------+---------+--------------------+
|      12|        1|                   4|
|      14|        1|                   4|
|      13|        1|                   4|
|      15|        1|                   4|
+--------+---------+--------------------+

In [ ]:
#from pyspark.sql import functions as F
import sys
from pyspark.sql.window import Window
import pyspark.sql.functions as F
from pyspark.sql.functions import col, count

tbase4_up = tbase4.filter(tbase4.no_pa_amt == 1)
result = tbase4_up.groupBy('failtype').agg(
    count('failtype').alias('Frequency'))

result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0))).show()

+--------+---------+--------------------+
|failtype|Frequency|Cumulative_Frequency|
+--------+---------+--------------------+
|      12|        1|                   1|
|      14|        1|                   2|
|      13|        1|                   3|
|      15|        1|                   4|
+--------+---------+--------------------+

In [ ]:
def proc_freq(data):
  data_up = data.filter(data.no_pa_amt == 1)
  result = data_up.groupBy('failtype').agg(count('failtype').alias('Frequency'))
  final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
  
  return final_res

In [ ]:
res = proc_freq(data=tbase4)
res.show()

+--------+---------+--------------------+
|failtype|Frequency|Cumulative_Frequency|
+--------+---------+--------------------+
|      12|        1|                   1|
|      14|        1|                   2|
|      13|        1|                   3|
|      15|        1|                   4|
+--------+---------+--------------------+

In [ ]:
# importing module
import pyspark

# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession

#import col
from pyspark.sql.functions import col, sum

# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list of student data
data = [["1", "sravan", "IT", 45000],
		["2", "ojaswi", "CS", 85000],
		["3", "rohith", "CS", 41000],
		["4", "sridevi", "IT", 56000],
		["5", "bobby", "ECE", 45000],
		["6", "gayatri", "ECE", 49000],
		["7", "gnanesh", "CS", 45000],
		["8", "bhanu", "Mech", 21000]
		]

# specify column names
columns = ['ID', 'NAME', 'DEPT', 'FEE']

# creating a dataframe from the lists of data
dataframe = spark.createDataFrame(data, columns)

dataframe.show()

+---+-------+----+-----+
| ID|   NAME|DEPT|  FEE|
+---+-------+----+-----+
|  1| sravan|  IT|45000|
|  2| ojaswi|  CS|85000|
|  3| rohith|  CS|41000|
|  4|sridevi|  IT|56000|
|  5|  bobby| ECE|45000|
|  6|gayatri| ECE|49000|
|  7|gnanesh|  CS|45000|
|  8|  bhanu|Mech|21000|
+---+-------+----+-----+

In [ ]:
# Groupby with DEPT with sum()
# to get FEE greater than 56700
dataframe.groupBy('DEPT').agg(sum(
'FEE').alias("Total Fee")).filter(
col('Total Fee') >= 56700).show()

+----+---------+
|DEPT|Total Fee|
+----+---------+
|  IT|   101000|
|  CS|   171000|
| ECE|    94000|
+----+---------+

p47

- data base_add;
- input vplus_acct_nbr org_code;
- datalines;
- 12 45
- 56 89
- 76 90
- 32 89
- ;
- run;

- data join address;
- input p_addr_code a_addr_code vplus_acct_nbr org_code;
- datalines;
- 13 67 12 45
- 14 76 76 90
- 23 67 98 74
- 65 78 32 89
- 98 56 23 19
- ;
- run;




proc sql;
*create table base_add as;
select a.*, b.p_addr_code, b.a_addr_code
from base_add a

left join address b
on a.vplus_acct_nbr = b.vplus_acct_nbr
and a.org_code = b.org_code
;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.getOrCreate()
data=([12,45],[56, 89], [76, 90], [32, 89])
columns=['vplus_acct_nbr', 'org_code'] 
base_add = spark.createDataFrame(data=data,schema=columns)
base_add.show()
base_add.createOrReplaceTempView("base_add")


data=([13, 67, 12, 45],[14, 76, 76, 90], [23, 67, 98, 74], [65, 78, 32, 89], [98, 56, 23, 19])
columns=['p_addr_code', 'a_addr_code', 'vplus_acct_nbr', 'org_code']
address = spark.createDataFrame(data=data,schema=columns)
address.show()
address.createOrReplaceTempView("address")

+--------------+--------+
|vplus_acct_nbr|org_code|
+--------------+--------+
|            12|      45|
|            56|      89|
|            76|      90|
|            32|      89|
+--------------+--------+

+-----------+-----------+--------------+--------+
|p_addr_code|a_addr_code|vplus_acct_nbr|org_code|
+-----------+-----------+--------------+--------+
|         13|         67|            12|      45|
|         14|         76|            76|      90|
|         23|         67|            98|      74|
|         65|         78|            32|      89|
|         98|         56|            23|      19|
+-----------+-----------+--------------+--------+

In [ ]:
result = spark.sql("""
	
select  a.*, b.p_addr_code, b.a_addr_code
from base_add a

left JOIN address b
on a.vplus_acct_nbr = b.vplus_acct_nbr
and a.org_code = b.org_code

""")

result.show()

+--------------+--------+-----------+-----------+
|vplus_acct_nbr|org_code|p_addr_code|a_addr_code|
+--------------+--------+-----------+-----------+
|            12|      45|         13|         67|
|            32|      89|         65|         78|
|            56|      89|       null|       null|
|            76|      90|         14|         76|
+--------------+--------+-----------+-----------+

p336

- data FINAL_ELIGIBLE_BASE_mmmyy_1;
- input crm_campaign_code;
- datalines;
- 12
- 22
- 34
- 56
- 78
- 98
- ;
- run;



- proc freq data=FINAL_ELIGIBLE_BASE_mmmyy_1;
- table crm_campaign_code/missing nocol norow nopct;run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.getOrCreate()
data=([12],[22], [34], [56], [78], [98])
columns=['crm_campaign_code'] 
FINAL_ELIGIBLE_BASE_mmmyy_1 = spark.createDataFrame(data=data,schema=columns)
FINAL_ELIGIBLE_BASE_mmmyy_1.show()
#FINAL_ELIGIBLE_BASE_mmmyy_1.createOrReplaceTempView("FINAL_ELIGIBLE_BASE_mmmyy_1")

+-----------------+
|crm_campaign_code|
+-----------------+
|               12|
|               22|
|               34|
|               56|
|               78|
|               98|
+-----------------+

In [ ]:
result = FINAL_ELIGIBLE_BASE_mmmyy_1.groupBy('crm_campaign_code').agg(F.count('crm_campaign_code').alias('Frequency'))
final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
final_res.show()

+-----------------+---------+--------------------+
|crm_campaign_code|Frequency|Cumulative_Frequency|
+-----------------+---------+--------------------+
|               22|        1|                   1|
|               34|        1|                   2|
|               12|        1|                   3|
|               98|        1|                   4|
|               56|        1|                   5|
|               78|        1|                   6|
+-----------------+---------+--------------------+

In [ ]:
def proc_freq(data):
  result = data.groupBy('crm_campaign_code').agg(F.count('crm_campaign_code').alias('Frequency'))
  final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  return final_res

res = proc_freq(data=FINAL_ELIGIBLE_BASE_mmmyy_1)  
res.show()

+-----------------+---------+--------------------+
|crm_campaign_code|Frequency|Cumulative_Frequency|
+-----------------+---------+--------------------+
|               22|        1|                   1|
|               34|        1|                   2|
|               12|        1|                   3|
|               98|        1|                   4|
|               56|        1|                   5|
|               78|        1|                   6|
+-----------------+---------+--------------------+

p16 Script 1

- data cb_all;
- input cif_id;
- datalines;
- 12
- 13
- 14
- 15
- 26
- ;
- run;


- data segment_p_date;
- input new_segment_ps $ tre_lite_subgroup $ cif_id;
- datalines;
- 'Treasures - Lite' 'xyz' 26
- 'uv' 'sham' 13
- 'sv' 'hsbc' 15
- 'dv' 'dbc' 12
- ;
- run;

proc sql;
create table cb_all as
select
	a*,
/*	b.new_segment_ps as new_segment_ps_ex,*/
	case when b.new_segment_ps = 'Treasures - Lite' then b.tre_lite_subgroup else ' ' end as tre_lite_subgroup  format=$26. length=26
from cb_all a
left join segment_p_date b
on a.cif_id = b.cif_id 
and b.new_segment_ps = 'Treasures - Lite';
run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.getOrCreate()
data=([12],[13], [14], [15], [26])
columns=['cif_id'] 
cb_all = spark.createDataFrame(data=data,schema=columns)
cb_all.show()
cb_all.createOrReplaceTempView("cb_all")


data=(['Treasures - Lite', 'Its Working', 26],['uv', 'sham', 13], ['sv', 'hsbc', 15], ['Treasures - Lite', 'Fine', 12])
columns=['new_segment_ps', 'tre_lite_subgroup', 'cif_id']
segment_p_date = spark.createDataFrame(data=data,schema=columns)
segment_p_date.show()
segment_p_date.createOrReplaceTempView("segment_p_date")

+------+
|cif_id|
+------+
|    12|
|    13|
|    14|
|    15|
|    26|
+------+

+----------------+-----------------+------+
|  new_segment_ps|tre_lite_subgroup|cif_id|
+----------------+-----------------+------+
|Treasures - Lite|      Its Working|    26|
|              uv|             sham|    13|
|              sv|             hsbc|    15|
|Treasures - Lite|             Fine|    12|
+----------------+-----------------+------+

In [ ]:
result = spark.sql("""

select
	a.*,
	case when b.new_segment_ps = 'Treasures - Lite' then b.tre_lite_subgroup else ' ' end as tre_lite_subgroup
from cb_all a
left join segment_p_date b
on a.cif_id = b.cif_id
and b.new_segment_ps = 'Treasures - Lite'
""")

result.show()


#ns.segment_${p_date}

+------+-----------------+
|cif_id|tre_lite_subgroup|
+------+-----------------+
|    12|             Fine|
|    13|                 |
|    14|                 |
|    15|                 |
|    26|      Its Working|
+------+-----------------+

p205 script 5

- data overall_exc_cust;
- input lb_cust_excl document_nbr lb_cust ;
- datalines;
- 56 'UV' 'Y'
- 78 'DV' 'N'
- 45 'DNB' 'Y'
- ;
- run;


- data base1c;
- input lb_cust_excl document_nbr lb_cust;
- datalines;
- 12 'JK' 'Y'
- 13 'Nk' 'N'
- 14 'BK' 'Y'
- ;
- run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.getOrCreate()
data=([56, 'UV', 'Y'],[78, 'DV', 'N'], [45, 'DNB', 'Y'])
columns=['lb_cust_excl', 'document_nbr', 'lb_cust']
overall_exc_cust = spark.createDataFrame(data=data,schema=columns)
overall_exc_cust.show()
overall_exc_cust.createOrReplaceTempView("overall_exc_cust")

data=([12, 'JK', 'Y'],[13, 'NK', 'N'], [14, 'Bk', 'Y'])
columns=['lb_cust_excl', 'document_nbr', 'lb_cust']
base1c = spark.createDataFrame(data=data,schema=columns)
base1c.show()
base1c.createOrReplaceTempView("base1c")

+------------+------------+-------+
|lb_cust_excl|document_nbr|lb_cust|
+------------+------------+-------+
|          56|          UV|      Y|
|          78|          DV|      N|
|          45|         DNB|      Y|
+------------+------------+-------+

+------------+------------+-------+
|lb_cust_excl|document_nbr|lb_cust|
+------------+------------+-------+
|          12|          JK|      Y|
|          13|          NK|      N|
|          14|          Bk|      Y|
+------------+------------+-------+

In [ ]:
result = spark.sql("""

set lb_cust_excl=1
where replace(upper(document_nbr), ' ', '') in (select replace(upper(document_nbr), ' ', '') from overall_exc_cust where lb_cust = 'Y' )

""")

result.show()

+------------+--------------------+
|         key|               value|
+------------+--------------------+
|lb_cust_excl|1\nwhere replace(...|
+------------+--------------------+

In [ ]:
result = spark.sql("""

select * from base1c where lb_cust = 'Y'


""")

result.show()

+------------+------------+-------+
|lb_cust_excl|document_nbr|lb_cust|
+------------+------------+-------+
|          12|          JK|      Y|
|          14|          Bk|      Y|
+------------+------------+-------+

p241

- data base1c;
- input fsupp card_line_curr_t ul_test_bk foreign_addr_party;
- datalines;
- 12 78 98 45
- 15 67 94 54
- 18 56 49 67
- 13 37 23 69
- ;
- run;

- proc freq data=base1c;
- table fsupp card_line_curr_t ul_test_bk foreign_addr_party/missing nocol - norow nopct;
- run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.getOrCreate()
data=([12, 78, 98, 45],[15, 67, 94, 54], [18, 56, 49, 67], [13, 37, 23, 69]) 
columns=['fsupp', 'card_line_curr_t', 'ul_test_bk', 'foreign_addr_party']
base1c = spark.createDataFrame(data=data,schema=columns)
base1c.show()
base1c.createOrReplaceTempView("base1c")

+-----+----------------+----------+------------------+
|fsupp|card_line_curr_t|ul_test_bk|foreign_addr_party|
+-----+----------------+----------+------------------+
|   12|              78|        98|                45|
|   15|              67|        94|                54|
|   18|              56|        49|                67|
|   13|              37|        23|                69|
+-----+----------------+----------+------------------+

In [ ]:
import sys
import pyspark.sql.functions as F
from pyspark.sql import Window
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

def proc_freq(data):

  result = data.groupBy('fsupp').agg(F.count('fsupp').alias('Frequency'))
  final_res = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  result1 = data.groupBy('card_line_curr_t').agg(F.count('card_line_curr_t').alias('Frequency'))
  final_res1 = result1.withColumn('Cumulative_Frequency', F.sum(result1.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))


  result2 = data.groupBy('ul_test_bk').agg(F.count('ul_test_bk').alias('Frequency'))
  final_res2 = result2.withColumn('Cumulative_Frequency', F.sum(result2.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
  

  result3 = data.groupBy('foreign_addr_party').agg(F.count('foreign_addr_party').alias('Frequency'))
  final_res3 = result3.withColumn('Cumulative_Frequency', F.sum(result3.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

  return final_res, final_res1, final_res2, final_res3


fsupp, card_line_curr_t, ul_test_bk, foreign_addr_party  = proc_freq(data = base1c)
fsupp.show()
card_line_curr_t.show()
ul_test_bk.show()
foreign_addr_party.show()

+-----+---------+--------------------+
|fsupp|Frequency|Cumulative_Frequency|
+-----+---------+--------------------+
|   12|        1|                   1|
|   15|        1|                   2|
|   13|        1|                   3|
|   18|        1|                   4|
+-----+---------+--------------------+

+----------------+---------+--------------------+
|card_line_curr_t|Frequency|Cumulative_Frequency|
+----------------+---------+--------------------+
|              67|        1|                   1|
|              78|        1|                   2|
|              56|        1|                   3|
|              37|        1|                   4|
+----------------+---------+--------------------+

+----------+---------+--------------------+
|ul_test_bk|Frequency|Cumulative_Frequency|
+----------+---------+--------------------+
|        94|        1|                   1|
|        98|        1|                   2|
|        49|        1|                   3|
|        23|        1|                   4|
+----------+---------+--------------------+

+------------------+---------+--------------------+
|foreign_addr_party|Frequency|Cumulative_Frequency|
+------------------+---------+--------------------+
|                54|        1|                   1|
|                45|        1|                   2|
|                67|        1|                   3|
|                69|        1|                   4|
+------------------+---------+--------------------+

p242

- data base1c;
- input age fage age60 expo_annual_income fincome rej hk_addr_ind foreign_addr_party;
- datalines;
- 23 45 55 43099 45000 "Yes" "Mumbai" "USA"
- 34 67 46 54219 67000 "Yes" "Pune" "England"
- 21 78 26 54789 78000 "No" "Nagpur" "Spain"
- 45 65 55 23765 65000 "No" "Chennai" "France"
- 34 90 36 34786 90000 "Yes" "Noida" "Russia"
- ;
- run;

- proc freq data=base1c;
- table age*fage  age*age60 expo_annual_income*fincome rej
- hk_addr_ind*foreign_addr_party/missing nocol norow nopct;
- run;

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.getOrCreate()
data=([23, 45, 55, 43099, 45000, "Yes", "Mumbai",  "USA"], [34, 67, 46, 54219, 67000, "Yes", "Pune", "England"], 
[21, 78, 26, 54789, 78000, "No",  "Nagpur", "Spain"], [45, 65, 55, 23765, 65000, "No", "Chennai", "France"],
[34, 90, 36, 34786, 90000, "Yes", "Noida", "Russia"]) 
columns= ['age', 'fage','age60','expo_annual_income','fincome','rej','hk_addr_ind','foreign_addr_party']
base1c = spark.createDataFrame(data=data,schema=columns)
base1c.show()
#base1c.createOrReplaceTempView("base1c")

+---+----+-----+------------------+-------+---+-----------+------------------+
|age|fage|age60|expo_annual_income|fincome|rej|hk_addr_ind|foreign_addr_party|
+---+----+-----+------------------+-------+---+-----------+------------------+
| 23|  45|   55|             43099|  45000|Yes|     Mumbai|               USA|
| 34|  67|   46|             54219|  67000|Yes|       Pune|           England|
| 21|  78|   26|             54789|  78000| No|     Nagpur|             Spain|
| 45|  65|   55|             23765|  65000| No|    Chennai|            France|
| 34|  90|   36|             34786|  90000|Yes|      Noida|            Russia|
+---+----+-----+------------------+-------+---+-----------+------------------+

In [ ]:
def proc_freq():
  w = Window.partitionBy().orderBy().rowsBetween( Window.unboundedPreceding,Window.currentRow)
  total_obs =base1c.count()
  df1 = base1c.groupby(['age', 'fage']).count().withColumnRenamed("count","Frequency")
  df2 = base1c.groupby(['age', 'age60']).count().withColumnRenamed("count","Frequency")
  df3 = base1c.groupby(['expo_annual_income', 'fincome']).count().withColumnRenamed("count","Frequency")
  df4=  base1c.groupBy('rej').agg(count('rej').alias('Frequency')).sort('rej').withColumn('Cumulative Frequency', sum(col('Frequency')).over(w))
  df5 = base1c.groupby(['hk_addr_ind', 'foreign_addr_party']).count().withColumnRenamed("count","Frequency")
  return df1, df2, df3, df4, df5
df1, df2, df3, df4, df5 = proc_freq()

In [ ]:
df1.show()
df2.show()
df3.show()
df4.show()
df5.show()

+---+----+---------+
|age|fage|Frequency|
+---+----+---------+
| 23|  45|        1|
| 34|  67|        1|
| 34|  90|        1|
| 45|  65|        1|
| 21|  78|        1|
+---+----+---------+

+---+-----+---------+
|age|age60|Frequency|
+---+-----+---------+
| 23|   55|        1|
| 34|   46|        1|
| 34|   36|        1|
| 21|   26|        1|
| 45|   55|        1|
+---+-----+---------+

+------------------+-------+---------+
|expo_annual_income|fincome|Frequency|
+------------------+-------+---------+
|             54219|  67000|        1|
|             43099|  45000|        1|
|             23765|  65000|        1|
|             34786|  90000|        1|
|             54789|  78000|        1|
+------------------+-------+---------+

+---+---------+--------------------+
|rej|Frequency|Cumulative Frequency|
+---+---------+--------------------+
| No|        2|                   2|
|Yes|        3|                   5|
+---+---------+--------------------+

+-----------+------------------+---------+
|hk_addr_ind|foreign_addr_party|Frequency|
+-----------+------------------+---------+
|       Pune|           England|        1|
|     Mumbai|               USA|        1|
|    Chennai|            France|        1|
|     Nagpur|             Spain|        1|
|      Noida|            Russia|        1|
+-----------+------------------+---------+

# DBS: Data Block: Script 5

DB42: For Reference

In [ ]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('app').getOrCreate()
data=[[1,3,5,7,6],[ 1,0,3,0,0],[1,1,1,1,1],[0,0,0,0,0],[1,2,3,4,5]]
columns=['unprefer_occp','su_vhr', 'su_hr','social_unrest','self_employ']
card_base1= spark.createDataFrame(data=data,schema=columns)
card_base1.show()

+-------------+------+-----+-------------+-----------+
|unprefer_occp|su_vhr|su_hr|social_unrest|self_employ|
+-------------+------+-----+-------------+-----------+
|            1|     3|    5|            7|          6|
|            1|     0|    3|            0|          0|
|            1|     1|    1|            1|          1|
|            0|     0|    0|            0|          0|
|            1|     2|    3|            4|          5|
+-------------+------+-----+-------------+-----------+

In [ ]:
from pyspark.sql.functions import lit
def proc_data(card_base1):
	card_base1=card_base1.withColumn('unprefer_occp',lit(0))
	card_base1=card_base1.withColumn('su_vhr',lit(0))
	card_base1=card_base1.withColumn('su_hr',lit(0))
	card_base1=card_base1.withColumn('social_unrest',lit(0))
	card_base1=card_base1.withColumn('self_employ',lit(0))
	return card_base1
card_base1=proc_data(card_base1)

In [ ]:
card_base1.show()

+-------------+------+-----+-------------+-----------+
|unprefer_occp|su_vhr|su_hr|social_unrest|self_employ|
+-------------+------+-----+-------------+-----------+
|            0|     0|    0|            0|          0|
|            0|     0|    0|            0|          0|
|            0|     0|    0|            0|          0|
|            0|     0|    0|            0|          0|
|            0|     0|    0|            0|          0|
+-------------+------+-----+-------------+-----------+

DB192

In [ ]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('app').getOrCreate()
data=[['30APR2021'],['26May2021'],['11Jan2021'],['12Feb2020'],['23Mar2020']]
columns=['expiry_date']
stage_final_au= spark.createDataFrame(data=data,schema=columns)
stage_final_au.show()

+-----------+
|expiry_date|
+-----------+
|  30APR2021|
|  26May2021|
|  11Jan2021|
|  12Feb2020|
|  23Mar2020|
+-----------+

In [ ]:
def proc_data(stage_final_au):

	stage_final_au=stage_final_au.withColumn('expiry_date',lit('30APR2022'))
	
	return stage_final_au
	
stage_final_au=proc_data(stage_final_au)

In [ ]:
stage_final_au.show()

+-----------+
|expiry_date|
+-----------+
|  30APR2022|
|  30APR2022|
|  30APR2022|
|  30APR2022|
|  30APR2022|
+-----------+

In [ ]:
#Amruta Code

import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('app').getOrCreate()
data=[[1], [3], [7]]  
columns=['index']
bs_consol_run_date = spark.createDataFrame(data=data,schema=columns)
bs_consol_run_date.show(20, False)

+-----+
|index|
+-----+
|1    |
|3    |
|7    |
+-----+

In [ ]:

def proc_data(data):

  batch_bs_consol_date = data
  return batch_bs_consol_date

In [ ]:
proc_data(data=bs_consol_run_date)

DataFrame[index: bigint]

DB215


- data a_base01_onboard_mth;
- input CIF_ID document_nbr XYZ ABC DEF;
- datalines;
- 12 45 87 32 98
- 13 65 98 23 75
- 14 55 67 34 90
- 15 26 37 89 95
- ;
- run;


- data temp;
- set a_base01_onboard_mth;
- keep CIF_ID document_nbr;
- run;

- proc print data=temp;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('app').getOrCreate()
data=[[12, 45, 87, 32, 98],[13, 65, 98, 23, 75],[14, 55, 67, 34, 90],[15, 26, 37, 89, 95]]  
columns=['CIF_ID', 'document_nbr', 'XYZ', 'ABC', 'DEF']
a_base01_onboard_mth= spark.createDataFrame(data=data,schema=columns)
a_base01_onboard_mth.show()

+------+------------+---+---+---+
|CIF_ID|document_nbr|XYZ|ABC|DEF|
+------+------------+---+---+---+
|    12|          45| 87| 32| 98|
|    13|          65| 98| 23| 75|
|    14|          55| 67| 34| 90|
|    15|          26| 37| 89| 95|
+------+------------+---+---+---+

In [ ]:
temp = a_base01_onboard_mth.select("CIF_ID", "document_nbr")
temp.show()

+------+------------+
|CIF_ID|document_nbr|
+------+------------+
|    12|          45|
|    13|          65|
|    14|          55|
|    15|          26|
+------+------------+

In [ ]:
def proc_data(data):
  temp = data.select("CIF_ID", "document_nbr")
  return temp

temp = proc_data(a_base01_onboard_mth)
temp.show()

+------+------------+
|CIF_ID|document_nbr|
+------+------------+
|    12|          45|
|    13|          65|
|    14|          55|
|    15|          26|
+------+------------+

DB257

- data fail;
- input fname $80.;
- datalines;
- prod abcd pqrst uvwxyz abcde lmnop pqrstuvwx
tan
- amruta sharvil prasanna jadhav At post prod 1234567890123567894321809654123456789012345678
- ;
- run;

- data fail;
- set fail;

- if index(fname,"prod");

- fname_fmt=trim(left(substr(fname,40,50)));
- fname_out=trim(left(substr(fname,40,29)||"_fail&&hhmmss1."));
- run;

- proc print data= fail;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('app').getOrCreate()
data=[["prod abcd pqrst uvwxyz abcde lmnop pqrstuvwx tanabs upendra"], ["amruta sharvil prasanna jadhav At post prod 1234567890123567894321809654123456789012345678"], ["upendra kumar"]]  
columns=['fname']
fail= spark.createDataFrame(data=data,schema=columns)
fail.show(20, False)

+------------------------------------------------------------------------------------------+
|fname                                                                                     |
+------------------------------------------------------------------------------------------+
|prod abcd pqrst uvwxyz abcde lmnop pqrstuvwx tanabs upendra                               |
|amruta sharvil prasanna jadhav At post prod 1234567890123567894321809654123456789012345678|
|upendra kumar                                                                             |
+------------------------------------------------------------------------------------------+

In [ ]:
from pyspark.sql.functions import col, lit
from pyspark.sql import functions as F

fail_df = fail.filter(col("fname").contains("prod"))
fail_final = fail_df.withColumn("fname_fmt", fail_df.fname.substr(40,50))
fail_final = fail_final.withColumn("fname_out1", fail_df.fname.substr(40,29))
fail_final = fail_final.withColumn("fname_out", F.concat(F.col('fname_out1'), lit("_fail&&hhmmss1.")))
fail_final = fail_final.drop("fname_out1")
fail_final.show(20, False)

+------------------------------------------------------------------------------------------+--------------------------------------------------+--------------------------------------------+
|fname                                                                                     |fname_fmt                                         |fname_out                                   |
+------------------------------------------------------------------------------------------+--------------------------------------------------+--------------------------------------------+
|prod abcd pqrst uvwxyz abcde lmnop pqrstuvwx tanabs upendra                               |tuvwx tanabs upendra                              |tuvwx tanabs upendra_fail&&hhmmss1.         |
|amruta sharvil prasanna jadhav At post prod 1234567890123567894321809654123456789012345678|prod 123456789012356789432180965412345678901234567|prod 123456789012356789432180_fail&&hhmmss1.|
+------------------------------------------------------------------------------------------+--------------------------------------------------+--------------------------------------------+

In [ ]:
def proc_data(data):
  data_df = data.filter(col("fname").contains("prod"))
  data_final = data_df.withColumn("fname_fmt", data_df.fname.substr(40,50))
  data_final = data_final.withColumn("fname_out1", data_df.fname.substr(40,29))
  data_final = data_final.withColumn("fname_out", F.concat(F.col('fname_out1'), lit("_fail&&hhmmss1.")))
  data_final = data_final.drop("fname_out1")
  return data_final

fail = proc_data(data=fail)
fail.show(20, False)

+------------------------------------------------------------------------------------------+--------------------------------------------------+--------------------------------------------+
|fname                                                                                     |fname_fmt                                         |fname_out                                   |
+------------------------------------------------------------------------------------------+--------------------------------------------------+--------------------------------------------+
|prod abcd pqrst uvwxyz abcde lmnop pqrstuvwx tanabs upendra                               |tuvwx tanabs upendra                              |tuvwx tanabs upendra_fail&&hhmmss1.         |
|amruta sharvil prasanna jadhav At post prod 1234567890123567894321809654123456789012345678|prod 123456789012356789432180965412345678901234567|prod 123456789012356789432180_fail&&hhmmss1.|
+------------------------------------------------------------------------------------------+--------------------------------------------------+--------------------------------------------+

DB110

- data base_final2;
- input acct_open_date DDMMYY10. New_acct_excl cms_grade $ cms_grade_excl;
- datalines;
- 12-04-2020 12 'AA' 15
- 17-03-2021 13 'CC' 12
- 22-07-2021 5  'KK' 19
- 25-09-2021 9  'ZZ' 25
- ;
- run;

- data base_final2;
- set base_final2;
- if acct_open_date>779398 then New_acct_excl=1;
- if cms_grade not in ('AA','BB','CC','DD','EE','FF','GG','HH','II') then cms_grade_excl=1;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('app').getOrCreate()
L1Md = 111111
data=[[120420, 0, 'AA', 0], [130520, 1, 'BB', 0], [171121, 0, 'ZZ', 0], [181220, 1, 'EE', 1], [111110, 0, "LL", 0]]  
columns=['acct_open_date', 'New_acct_excl', 'cms_grade', 'cms_grade_excl']
base_final2= spark.createDataFrame(data=data,schema=columns)
base_final2.show()

+--------------+-------------+---------+--------------+
|acct_open_date|New_acct_excl|cms_grade|cms_grade_excl|
+--------------+-------------+---------+--------------+
|        120420|            0|       AA|             0|
|        130520|            1|       BB|             0|
|        171121|            0|       ZZ|             0|
|        181220|            1|       EE|             1|
|        111110|            0|       LL|             0|
+--------------+-------------+---------+--------------+

In [ ]:
from pyspark.sql.functions import *
code = ['AA','BB','CC','DD','EE','FF','GG','HH','II']
base_final2 = base_final2.withColumn("New_acct_excl", when(base_final2.acct_open_date > L1Md, 1).otherwise(base_final2["New_acct_excl"]))
base_final2 = base_final2.withColumn("cms_grade_excl", when(~base_final2['cms_grade'].isin(code), 1).otherwise(base_final2["cms_grade_excl"]))
base_final2.show()

+--------------+-------------+---------+--------------+
|acct_open_date|New_acct_excl|cms_grade|cms_grade_excl|
+--------------+-------------+---------+--------------+
|        120420|            1|       AA|             0|
|        130520|            1|       BB|             0|
|        171121|            1|       ZZ|             1|
|        181220|            1|       EE|             1|
|        111110|            0|       LL|             1|
+--------------+-------------+---------+--------------+

In [ ]:
def proc_data(data):
  L1Md = 111111
  code = ['AA','BB','CC','DD','EE','FF','GG','HH','II']
  data = data.withColumn("New_acct_excl", when(base_final2.acct_open_date > L1Md, 1).otherwise(base_final2["New_acct_excl"]))
  data = data.withColumn("cms_grade_excl", when(~base_final2['cms_grade'].isin(code), 1).otherwise(base_final2["cms_grade_excl"]))
  return data
base_final2 = proc_data(data=base_final2)  
base_final2.show()

+--------------+-------------+---------+--------------+
|acct_open_date|New_acct_excl|cms_grade|cms_grade_excl|
+--------------+-------------+---------+--------------+
|        120420|            1|       AA|             0|
|        130520|            1|       BB|             0|
|        171121|            1|       ZZ|             1|
|        181220|            1|       EE|             1|
|        111110|            0|       LL|             1|
+--------------+-------------+---------+--------------+

In [ ]:
## By Monika
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.appName('pyspark - example join').getOrCreate()
data=[['L1Md','AA'],['HH','II'],['BB','PP'],['EE','FF'],['HH','TT'],['MM','TT'],['GG','CC']]
columns=['acct_open_date', 'cms_grade']
base_final2= spark.createDataFrame(data=data,schema=columns)
base_final2.show()

+--------------+---------+
|acct_open_date|cms_grade|
+--------------+---------+
|          L1Md|       AA|
|            HH|       II|
|            BB|       PP|
|            EE|       FF|
|            HH|       TT|
|            MM|       TT|
|            GG|       CC|
+--------------+---------+

In [ ]:
def data_null(df):
  df=df.withColumn('New_acct_excl',when((df.acct_open_date > 'L1Md'), '1'))
  df=df.withColumn('cms_grade_excl',when(~(df.cms_grade.isin('AA','BB','CC','DD','EE','FF','GG','HH','II')), '1'))
  return df
base_final2=data_null(df=base_final2)
base_final2.show()

+--------------+---------+-------------+--------------+
|acct_open_date|cms_grade|New_acct_excl|cms_grade_excl|
+--------------+---------+-------------+--------------+
|          L1Md|       AA|         null|          null|
|            HH|       II|         null|          null|
|            BB|       PP|         null|             1|
|            EE|       FF|         null|          null|
|            HH|       TT|         null|             1|
|            MM|       TT|            1|             1|
|            GG|       CC|         null|          null|
+--------------+---------+-------------+--------------+

Db236

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [["100"],["run_date_k1w"],["25-12-20"],["0"],["3"]]
columns=["as_of_date1"]
spark = SparkSession.builder.appName('dataset').getOrCreate()
bottom_sheet_individ=spark.createDataFrame(data=data,schema=columns)
bottom_sheet_individ.show()

+------------+
| as_of_date1|
+------------+
|         100|
|run_date_k1w|
|    25-12-20|
|           0|
|           3|
+------------+

In [ ]:
def proc_data(df):
  df=df.where(df.as_of_date1 <= 'run_date_k1w').drop('as_of_date1')
  return df
bottom_sheet_individ=proc_data(df=bottom_sheet_individ)
bottom_sheet_individ.show()

++
||
++
||
||
||
||
||
++

### DBS_Ratna

p20

- data parameterfile;
- input prodtype $ prodtype1 $ ABC;
- datalines;
- Z C 12
- B A 11
- A D 9
- D B 5
- ;
- run;


- proc sort data=parameterfile out=_parameterfile_;
- by prodtype prodtype1;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [["Z", "C", 12], ["B", "A", 11], ["A", "D", 9], ["D", "B", 5]]
columns=["prodtype", "prodtype1", "ABC"]
spark = SparkSession.builder.appName('dataset').getOrCreate()
parameterfile=spark.createDataFrame(data=data,schema=columns)
parameterfile.show()

+--------+---------+---+
|prodtype|prodtype1|ABC|
+--------+---------+---+
|       Z|        C| 12|
|       B|        A| 11|
|       A|        D|  9|
|       D|        B|  5|
+--------+---------+---+

In [ ]:
_parameterfile = parameterfile.orderBy('prodtype','prodtype1')
_parameterfile.show()

+--------+---------+---+
|prodtype|prodtype1|ABC|
+--------+---------+---+
|       A|        D|  9|
|       B|        A| 11|
|       D|        B|  5|
|       Z|        C| 12|
+--------+---------+---+

In [ ]:
def proc_sort(data):
  _parameterfile = data.orderBy('prodtype', 'prodtype1')
  return _parameterfile

_parameterfile = proc_sort(data = parameterfile)
_parameterfile.show()

+--------+---------+---+
|prodtype|prodtype1|ABC|
+--------+---------+---+
|       A|        D|  9|
|       B|        A| 11|
|       D|        B|  5|
|       Z|        C| 12|
+--------+---------+---+

p21

- data entitymart;
- input bal_aum k_pdt;
- datalines;
- 12 45
- 13 55
- 14 78
- 15 89
- ;
- run;

- proc datasets library=work;
- modify entitymart;
- rename bal_aum=aum k_pdt = k_pdt_main;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [[12, 45], [13, 55], [14, 78], [15, 89]]
columns=["bal_aum", "k_pdt"]
spark = SparkSession.builder.appName('sas2py').getOrCreate()
entitymart=spark.createDataFrame(data=data,schema=columns)
entitymart.show()

+-------+-----+
|bal_aum|k_pdt|
+-------+-----+
|     12|   45|
|     13|   55|
|     14|   78|
|     15|   89|
+-------+-----+

In [ ]:
entitymart = entitymart.withColumnRenamed("bal_aum", "aum").withColumnRenamed("k_pdt", "k_pdt_main")
entitymart.show()

+---+----------+
|aum|k_pdt_main|
+---+----------+
| 12|        45|
| 13|        55|
| 14|        78|
| 15|        89|
+---+----------+

In [ ]:
def proc_dataset(data):
  entitymart = data.withColumnRenamed("bal_aum", "aum").withColumnRenamed("k_pdt", "k_pdt_main")
  return entitymart
entitymart = proc_dataset(data=entitymart)
entitymart.show()

+---+----------+
|aum|k_pdt_main|
+---+----------+
| 12|        45|
| 13|        55|
| 14|        78|
| 15|        89|
+---+----------+

p22

- data tciscustmth;
- input newcinsfx new_code code_done;
- datalines;
- 12 4 1
- 25 3 0
- 44 2 1
- 10 2 1
- 11 1 0
- ;
- run;

- proc sort data=tciscustmth; 
- by newcinsfx; 
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [[12, 4, 1], [25, 3, 0], [44, 2, 1], [10, 2, 1], [11, 1, 0]]
columns=["newcinsfx", "new_code", "code_done"]
spark = SparkSession.builder.appName('sas2py').getOrCreate()
tciscustmth=spark.createDataFrame(data=data,schema=columns)
tciscustmth.show()

+---------+--------+---------+
|newcinsfx|new_code|code_done|
+---------+--------+---------+
|       12|       4|        1|
|       25|       3|        0|
|       44|       2|        1|
|       10|       2|        1|
|       11|       1|        0|
+---------+--------+---------+

In [ ]:
def proc_sort(data):
  sorted_tciscustmth = data.orderBy('newcinsfx')
  return sorted_tciscustmth

tciscustmth = proc_sort(data = tciscustmth)
tciscustmth.show()

+---------+--------+---------+
|newcinsfx|new_code|code_done|
+---------+--------+---------+
|       10|       2|        1|
|       11|       1|        0|
|       12|       4|        1|
|       25|       3|        0|
|       44|       2|        1|
+---------+--------+---------+

p23

- data entitymart;
- input entity $ code;
- datalines;
- Car 11
- Box 8
- Machine 6
- Laptop 12
- Drone 13
- LaptopX 90
- ;
- run;

- proc sql;
- create table num_entity as
- select entity
- from entitymart(keep=entity)
- having length(trim(entity))=max(length(trim(entity)));
- quit;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [["Car", 11], ["Box", 8], ["Machine", 6], ["Laptop", 12], ["Drone", 13], ["LaptopX", 90]]
columns=["entity", "code"]
spark = SparkSession.builder.appName('sas2py').getOrCreate()
entitymart=spark.createDataFrame(data=data,schema=columns)
entitymart.createOrReplaceTempView("entitymart")
entitymart.show()

+-------+----+
| entity|code|
+-------+----+
|    Car|  11|
|    Box|   8|
|Machine|   6|
| Laptop|  12|
|  Drone|  13|
|LaptopX|  90|
+-------+----+

In [ ]:
spark.sql("select max(char_length(trim(entity))) as max_length from entitymart").show()

+----------+
|max_length|
+----------+
|         7|
+----------+

In [ ]:
spark.sql("select entity from entitymart where char_length(trim(entity)) in (select max(char_length(trim(entity))) from entitymart)").show()

+-------+
| entity|
+-------+
|Machine|
|LaptopX|
+-------+

p24

- data entity1;
- input newcinsfx entity $ ABCD;
- datalines;
- 22 Car 7
- 18 Drone 8
- 14 Laptop 10
- 10 Computer 11
- 18 Drone 8
- ;
- run;

- proc sort data=entity1 out=entity2 nodupkey;
- by newcinsfx entity;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [[22, "Car", 7], [18, "Drone", 8], [14, "Laptop", 10], [10, "Computer", 11], [18, "Drone", 8]] 
columns=["newcinsfx", "entity", "ABCD"] 
spark = SparkSession.builder.appName('sas2py').getOrCreate()
entity1=spark.createDataFrame(data=data,schema=columns)
entity1.show()

+---------+--------+----+
|newcinsfx|  entity|ABCD|
+---------+--------+----+
|       22|     Car|   7|
|       18|   Drone|   8|
|       14|  Laptop|  10|
|       10|Computer|  11|
|       18|   Drone|   8|
+---------+--------+----+

In [ ]:
entity1.columns

['newcinsfx', 'entity', 'ABCD']

In [ ]:
def proc_sort(data):
  nodup_data = data.dropDuplicates()
  sorted_data = nodup_data.orderBy('newcinsfx', 'entity')
  return sorted_data

entity2 = proc_sort(data = entity1)
entity2.show()

+---------+--------+----+
|newcinsfx|  entity|ABCD|
+---------+--------+----+
|       10|Computer|  11|
|       14|  Laptop|  10|
|       18|   Drone|   8|
|       22|     Car|   7|
+---------+--------+----+

p33

- data tr_entitymart_yyyymm;
- input newcinsfx1 bdic1 aum bal_dep
- bal_trsy bal_inv bal_oth_inv ost_loans
- prem_ins1_gi prem_ins1_li;
- datalines;
- 11 12 13 14 15 16 17 18 19 20
- 21 22 23 24 25 26 27 28 29 30
- 11 21 31 41 51 61 71 81 91 30
- 21 22 32 42 52 62 72 82 82 80
- 11 67 89 98 67 45 23 45 67 89
- 13 67 54 45 67 78 89 98 35 23
- 15 17 18 34 12 14 15 17 28 34
- ;
- run;

- proc sql;
- create table en as
- select
- newcinsfx1,
- bdic1,
- sum(aum) as aum,
- sum(bal_dep) as bal_dep,
- sum(bal_trsy) as bal_trsy,
- sum(bal_inv) as bal_inv,
- sum(bal_oth_inv) as bal_oth_inv,
- sum(ost_loans) as ost_loans,
- sum(prem_ins1_gi) as prem_ins1_gi,
- sum(prem_ins1_li) as prem_ins1_li
- FROM tr_entitymart_yyyymm
- group by newcinsfx1;
- quit;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], [21, 22, 23, 24, 25, 26, 27, 28, 29, 30], 
       [11, 21, 31, 41, 51, 61, 71, 81, 91, 30], [21, 22, 32, 42, 52, 62, 72, 82, 82, 80], 
       [11, 67, 89, 98, 67, 45, 23, 45, 67, 89], [13, 67, 54, 45, 67, 78, 89, 98, 35, 23],
       [15, 17, 18, 34, 12, 14, 15, 17, 28, 34]
       
       ] 
columns=['newcinsfx1','bdic1', 'aum', 'bal_dep', 'bal_trsy', 'bal_inv', 'bal_oth_inv', 'ost_loans', 'prem_ins1_gi', 'prem_ins1_li']
spark = SparkSession.builder.appName('sas2py').getOrCreate()
tr_entitymart_yyyymm=spark.createDataFrame(data=data,schema=columns)
tr_entitymart_yyyymm.createOrReplaceTempView("tr_entitymart_yyyymm")
tr_entitymart_yyyymm.show()

+----------+-----+---+-------+--------+-------+-----------+---------+------------+------------+
|newcinsfx1|bdic1|aum|bal_dep|bal_trsy|bal_inv|bal_oth_inv|ost_loans|prem_ins1_gi|prem_ins1_li|
+----------+-----+---+-------+--------+-------+-----------+---------+------------+------------+
|        11|   12| 13|     14|      15|     16|         17|       18|          19|          20|
|        21|   22| 23|     24|      25|     26|         27|       28|          29|          30|
|        11|   21| 31|     41|      51|     61|         71|       81|          91|          30|
|        21|   22| 32|     42|      52|     62|         72|       82|          82|          80|
|        11|   67| 89|     98|      67|     45|         23|       45|          67|          89|
|        13|   67| 54|     45|      67|     78|         89|       98|          35|          23|
|        15|   17| 18|     34|      12|     14|         15|       17|          28|          34|
+----------+-----+---+-------+--------+-------+-----------+---------+------------+------------+

In [ ]:
spark.sql("""

select
newcinsfx1,
sum(aum) as aum,
sum(bal_dep) as bal_dep,
sum(bal_trsy) as bal_trsy,
sum(bal_inv) as bal_inv,
sum(bal_oth_inv) as bal_oth_inv,
sum(ost_loans) as ost_loans,
sum(prem_ins1_gi) as prem_ins1_gi,
sum(prem_ins1_li) as prem_ins1_li
FROM tr_entitymart_yyyymm
group by newcinsfx1 

""").show()

+----------+---+-------+--------+-------+-----------+---------+------------+------------+
|newcinsfx1|aum|bal_dep|bal_trsy|bal_inv|bal_oth_inv|ost_loans|prem_ins1_gi|prem_ins1_li|
+----------+---+-------+--------+-------+-----------+---------+------------+------------+
|        11|133|    153|     133|    122|        111|      144|         177|         139|
|        21| 55|     66|      77|     88|         99|      110|         111|         110|
|        13| 54|     45|      67|     78|         89|       98|          35|          23|
|        15| 18|     34|      12|     14|         15|       17|          28|          34|
+----------+---+-------+--------+-------+-----------+---------+------------+------------+

p37

- data en;
- input newcinsfx1 bdic1 aum bal_dep bal_inv bal_oth_inv ost_loans prem_ins1_gi prem_ins1_li;
- datalines;
- 12 13 14 15 16 17 18 22
- 11 22 33 45 67 89 56 23
- 34 67 89 34 56 34 78 24
- 44 55 77 88 99 34 23 45
- 21 32 43 54 65 76 87 56
- ;
- run;

- data datamart;
- input newcinsfx bdic aum sc_bal_dep sc_bal_inv sc_bal_oth_inv sc_ost_loans prem_ins1_gi prem_ins1_li;
- datalines;
- 12 13 34 15 66 17 18 22
- 91 42 33 45 67 89 56 23
- 44 77 89 39 56 34 68 24
- 94 55 57 88 99 84 23 45
- 21 32 43 54 65 76 87 56
- ;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [
       [12, 13, 14, 15, 16, 17, 18, 22, 23], [11, 22, 33, 45, 67, 89, 56, 23, 45], 
       [34, 67, 89, 34, 56, 34, 78, 24, 67], [44, 55, 77, 88, 99, 34, 23, 45, 89], 
       [21, 32, 43, 54, 65, 76, 87, 56, 78], [13, 67, 54, 45, 67, 78, 89, 98, 67],
       [15, 17, 18, 34, 12, 14, 15, 17, 56]
       
       ] 
columns=['newcinsfx1','bdic1', 'aum', 'bal_dep', 'bal_inv', 'bal_oth_inv', 'ost_loans', 'prem_ins1_gi', 'prem_ins1_li']
spark = SparkSession.builder.appName('sas2py').getOrCreate()
en=spark.createDataFrame(data=data,schema=columns)
en.createOrReplaceTempView("en")
en.show()

+----------+-----+---+-------+-------+-----------+---------+------------+------------+
|newcinsfx1|bdic1|aum|bal_dep|bal_inv|bal_oth_inv|ost_loans|prem_ins1_gi|prem_ins1_li|
+----------+-----+---+-------+-------+-----------+---------+------------+------------+
|        12|   13| 14|     15|     16|         17|       18|          22|          23|
|        11|   22| 33|     45|     67|         89|       56|          23|          45|
|        34|   67| 89|     34|     56|         34|       78|          24|          67|
|        44|   55| 77|     88|     99|         34|       23|          45|          89|
|        21|   32| 43|     54|     65|         76|       87|          56|          78|
|        13|   67| 54|     45|     67|         78|       89|          98|          67|
|        15|   17| 18|     34|     12|         14|       15|          17|          56|
+----------+-----+---+-------+-------+-----------+---------+------------+------------+

In [ ]:
data= [
       [34, 13, 14, 15, 16, 17, 18, 22, 23], [15, 23, 33, 45, 67, 89, 56, 23, 45], 
       [34, 67, 83, 34, 56, 33, 78, 24, 67], [44, 55, 77, 88, 99, 34, 23, 43, 89], 
       [26, 31, 44, 51, 65, 76, 87, 56, 78], [19, 67, 58, 45, 60, 78, 89, 98, 67],
       [45, 17, 18, 34, 12, 14, 15, 17, 56]
       
       ] 
columns=['newcinsfx','bdic', 'aum', 'sc_bal_dep', 'sc_bal_inv', 'sc_bal_oth_inv', 'sc_ost_loans', 'prem_ins1_gi', 'prem_ins1_li']
spark = SparkSession.builder.appName('sas2py').getOrCreate()
datamart=spark.createDataFrame(data=data,schema=columns)
datamart.createOrReplaceTempView("datamart")
datamart.show()

+---------+----+---+----------+----------+--------------+------------+------------+------------+
|newcinsfx|bdic|aum|sc_bal_dep|sc_bal_inv|sc_bal_oth_inv|sc_ost_loans|prem_ins1_gi|prem_ins1_li|
+---------+----+---+----------+----------+--------------+------------+------------+------------+
|       34|  13| 14|        15|        16|            17|          18|          22|          23|
|       15|  23| 33|        45|        67|            89|          56|          23|          45|
|       34|  67| 83|        34|        56|            33|          78|          24|          67|
|       44|  55| 77|        88|        99|            34|          23|          43|          89|
|       26|  31| 44|        51|        65|            76|          87|          56|          78|
|       19|  67| 58|        45|        60|            78|          89|          98|          67|
|       45|  17| 18|        34|        12|            14|          15|          17|          56|
+---------+----+---+----------+----------+--------------+------------+------------+------------+

In [ ]:
compare= spark.sql("""

select a.newcinsfx1, a.bdic1, a.aum as aum_E, b.aum as aum_D, a.bal_dep as dep_E, b.sc_bal_dep as dep_D, 
a.bal_inv as inv_E, b.sc_bal_inv as inv_D, a.bal_oth_inv as oth_E, b.sc_bal_oth_inv as oth_D, 
a.ost_loans as loans_E, b.sc_ost_loans as loans_D, a.prem_ins1_gi as prem_ins1_gi_E, b.prem_ins1_gi as prem_ins1_gi_D 
from en as a inner join datamart as b on a.newcinsfx1=b.newcinsfx and a.bdic1=b.bdic where a.aum-b.aum >1 or 
a.bal_dep-b.sc_bal_dep > 1 or a.bal_inv-b.sc_bal_inv > 1 or a.bal_oth_inv-b.sc_bal_oth_inv > 1 or 
a.prem_ins1_li != b.prem_ins1_li or a.ost_loans - b.sc_ost_loans>1 or a.prem_ins1_gi - b.prem_ins1_gi>1

""")

compare.show()

+----------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------+-------+--------------+--------------+
|newcinsfx1|bdic1|aum_E|aum_D|dep_E|dep_D|inv_E|inv_D|oth_E|oth_D|loans_E|loans_D|prem_ins1_gi_E|prem_ins1_gi_D|
+----------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------+-------+--------------+--------------+
|        34|   67|   89|   83|   34|   34|   56|   56|   34|   33|     78|     78|            24|            24|
|        44|   55|   77|   77|   88|   88|   99|   99|   34|   34|     23|     23|            45|            43|
+----------+-----+-----+-----+-----+-----+-----+-----+-----+-----+-------+-------+--------------+--------------+

DB2

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [
       ["Yes", "One", "Upendra", "Daffodil", 15, "March", "13Mar2022", 11, "daffodil_csv", 'PCM', 'yes', 'No', 'deactivate'], 
       ["Yes", "One", "Deepak", "Daffodil", 15, "April", "13Apr2022", 1, "daffodil2_csv", 'Comm', 'No', 'No', 'deactivate'], 
       ["No", "two", "Shweta", "Falcon", 10, "Feb", "13feb2022", 11, "falcon_csv", 'Arts', 'yes', 'yes', 'activate'],
       ["Yes", "three", "Vijay", "Harier", 15, "Dec", "13Dec2022", 12, "har_csv", 'pcm', 'no', 'yes', 'deactivate'],
       ["Yes", "One", "Roshan", "Daffodil", 10, "Sep", "13Sep2022", 11, "daffodil3_csv", 'comm', 'yes', 'yes', 'activate']
       ] 
columns=['right','type', 'Owner', 'Group', 'Size', 'Month', 'date', 'time', 'file_Name', 'depart', 'approve', 'opt', 'status']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
ps_list=spark.createDataFrame(data=data,schema=columns)
ps_list.show()

+-----+-----+-------+--------+----+-----+---------+----+-------------+------+-------+---+----------+
|right| type|  Owner|   Group|Size|Month|     date|time|    file_Name|depart|approve|opt|    status|
+-----+-----+-------+--------+----+-----+---------+----+-------------+------+-------+---+----------+
|  Yes|  One|Upendra|Daffodil|  15|March|13Mar2022|  11| daffodil_csv|   PCM|    yes| No|deactivate|
|  Yes|  One| Deepak|Daffodil|  15|April|13Apr2022|   1|daffodil2_csv|  Comm|     No| No|deactivate|
|   No|  two| Shweta|  Falcon|  10|  Feb|13feb2022|  11|   falcon_csv|  Arts|    yes|yes|  activate|
|  Yes|three|  Vijay|  Harier|  15|  Dec|13Dec2022|  12|      har_csv|   pcm|     no|yes|deactivate|
|  Yes|  One| Roshan|Daffodil|  10|  Sep|13Sep2022|  11|daffodil3_csv|  comm|    yes|yes|  activate|
+-----+-----+-------+--------+----+-----+---------+----+-------------+------+-------+---+----------+

In [ ]:
ps_list.select('right','type', 'Owner', 'Group', 'Size', 'Month', 'date', 'time', 'file_Name').show()

+-----+-----+-------+--------+----+-----+---------+----+-------------+
|right| type|  Owner|   Group|Size|Month|     date|time|    file_Name|
+-----+-----+-------+--------+----+-----+---------+----+-------------+
|  Yes|  One|Upendra|Daffodil|  15|March|13Mar2022|  11| daffodil_csv|
|  Yes|  One| Deepak|Daffodil|  15|April|13Apr2022|   1|daffodil2_csv|
|   No|  two| Shweta|  Falcon|  10|  Feb|13feb2022|  11|   falcon_csv|
|  Yes|three|  Vijay|  Harier|  15|  Dec|13Dec2022|  12|      har_csv|
|  Yes|  One| Roshan|Daffodil|  10|  Sep|13Sep2022|  11|daffodil3_csv|
+-----+-----+-------+--------+----+-----+---------+----+-------------+

In [ ]:
x = ps_list.collect()[1:]  # x will be list
df_x = spark.createDataFrame(data=x)
df_x.show()

+-----+-----+------+--------+----+-----+---------+----+-------------+------+-------+---+----------+
|right| type| Owner|   Group|Size|Month|     date|time|    file_Name|depart|approve|opt|    status|
+-----+-----+------+--------+----+-----+---------+----+-------------+------+-------+---+----------+
|  Yes|  One|Deepak|Daffodil|  15|April|13Apr2022|   1|daffodil2_csv|  Comm|     No| No|deactivate|
|   No|  two|Shweta|  Falcon|  10|  Feb|13feb2022|  11|   falcon_csv|  Arts|    yes|yes|  activate|
|  Yes|three| Vijay|  Harier|  15|  Dec|13Dec2022|  12|      har_csv|   pcm|     no|yes|deactivate|
|  Yes|  One|Roshan|Daffodil|  10|  Sep|13Sep2022|  11|daffodil3_csv|  comm|    yes|yes|  activate|
+-----+-----+------+--------+----+-----+---------+----+-------------+------+-------+---+----------+

In [ ]:
def proc_data(data):
  df = data.select('right','type', 'Owner', 'Group', 'Size', 'Month', 'date', 'time', 'file_Name')
  collection = df.collect()[1:]
  collected_df = spark.createDataFrame(data=collection)
  return collected_df
abc = proc_data(data=ps_list)
abc.show()

+-----+-----+------+--------+----+-----+---------+----+-------------+
|right| type| Owner|   Group|Size|Month|     date|time|    file_Name|
+-----+-----+------+--------+----+-----+---------+----+-------------+
|  Yes|  One|Deepak|Daffodil|  15|April|13Apr2022|   1|daffodil2_csv|
|   No|  two|Shweta|  Falcon|  10|  Feb|13feb2022|  11|   falcon_csv|
|  Yes|three| Vijay|  Harier|  15|  Dec|13Dec2022|  12|      har_csv|
|  Yes|  One|Roshan|Daffodil|  10|  Sep|13Sep2022|  11|daffodil3_csv|
+-----+-----+------+--------+----+-----+---------+----+-------------+

DB19

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [["Bus/dddd"],
       ["Train/nddd"],
       ["Bike/gfff"],
       ["Car/tyy"]]

columns=['entity'] 

spark = SparkSession.builder.appName('sas2py').getOrCreate()
entitymart=spark.createDataFrame(data=data,schema=columns)
entitymart.show()

+----------+
|    entity|
+----------+
|  Bus/dddd|
|Train/nddd|
| Bike/gfff|
|   Car/tyy|
+----------+

In [ ]:
from pyspark.sql import functions as F
def func_1837(data):
  data = data.select(['entity'])
  data = data.withColumn('cust_cnt', length(rtrim(trim(data.entity)))-length(regexp_replace(data.entity, '/', ''))+1)
  cust_cnt = data.select('cust_cnt').rdd.flatMap(lambda x: x).collect()

  for i in range (0,cust_cnt[0]):
    data = data.withColumn('newcinsfx', F.split(F.col('entity'), '/')[0])
    data = data.withColumn('newcinsfx1', F.split(F.col('entity'), '/')[1])
    continue
    
  entity1 = data.select('entity','newcinsfx', 'newcinsfx1')
  return entity1

entity1 = func_1837(entitymart)
entity1.show()

+----------+---------+----------+
|    entity|newcinsfx|newcinsfx1|
+----------+---------+----------+
|  Bus/dddd|      Bus|      dddd|
|Train/nddd|    Train|      nddd|
| Bike/gfff|     Bike|      gfff|
|   Car/tyy|      Car|       tyy|
+----------+---------+----------+

In [ ]:
#Function declaration...
#def func_7010(entitymart):
from pyspark.sql.functions import regexp_replace, col
data = entitymart
data = data.select(['entity'])
data = data.withColumn('cust_cnt', length(trim(data.entity))- length(regexp_replace(data.entity, "/", ""))+1)

In [ ]:
data.show()

+----------+--------+
|    entity|cust_cnt|
+----------+--------+
|       Car|       1|
|   Lap/top|       2|
|Comp/ut/er|       3|
|      Bike|       1|
+----------+--------+

DBS Ratna: Script2

p16
- data clieln;
- input newcinsfx $ product $;
- datalines;
- ab CLI
- ba CDI
- cd CLI
- dc CLI
- ef MBI
- fg VHI
- hi CLI
- ;
- run;

- proc sql;
- create table cli2 as
- select distinct newcinsfx, 1 as f_p6m_txn_cli_tpc
- from clieln
- where product = 'CLI';
- quit;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [["ab", "CLI"],
       ["ba", "CDI"],
       ["CD", "CLI"],
       ["dc", "CLI"],
       ["ef", "MBI"],
       ["fg", "VHI"],
       ["hi", "CLI"]]

columns=['newcinsfx', 'product']      

spark = SparkSession.builder.appName('sas2py').getOrCreate()
clieln=spark.createDataFrame(data=data,schema=columns)
clieln.createOrReplaceTempView("clieln")
clieln.show()

+---------+-------+
|newcinsfx|product|
+---------+-------+
|       ab|    CLI|
|       ba|    CDI|
|       CD|    CLI|
|       dc|    CLI|
|       ef|    MBI|
|       fg|    VHI|
|       hi|    CLI|
+---------+-------+

In [ ]:
result = spark.sql("""

select distinct newcinsfx, 1 as f_p6m_txn_cli_tpc from clieln where product = 'CLI'

""")

result.show()

+---------+-----------------+
|newcinsfx|f_p6m_txn_cli_tpc|
+---------+-----------------+
|       ab|                1|
|       CD|                1|
|       dc|                1|
|       hi|                1|
+---------+-----------------+

p44

- data wp_p6m;
- input PARTY_ID;
- datalines;
- 25
- 27
- 29
- 30
- 32
- 34
- ;
- run;


- data wp_curr;
- input PARTY_ID;
- datalines;
- 52
- 27
- 98
- 30
- 23
- 34
- ;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [[25],
       [27],
       [29],
       [30],
       [32],
       [34],
       ]

columns=['PARTY_ID']      

spark = SparkSession.builder.appName('sas2py').getOrCreate()
wp_p6m=spark.createDataFrame(data=data,schema=columns)
wp_p6m.createOrReplaceTempView("wp_p6m")
wp_p6m.show()

data= [[52],
       [27],
       [98],
       [30],
       [23],
       [34]]
columns=['PARTY_ID']      

spark = SparkSession.builder.appName('sas2py').getOrCreate()
wp_curr=spark.createDataFrame(data=data,schema=columns)
wp_curr.createOrReplaceTempView("wp_curr")
wp_curr.show()

+--------+
|PARTY_ID|
+--------+
|      25|
|      27|
|      29|
|      30|
|      32|
|      34|
+--------+

+--------+
|PARTY_ID|
+--------+
|      52|
|      27|
|      98|
|      30|
|      23|
|      34|
+--------+

In [ ]:
result = spark.sql("""

select coalesce(a.PARTY_ID,b.PARTY_ID) as PARTY_ID , a.*, b.* from wp_p6m a FULL OUTER JOIN wp_curr b on b.PARTY_ID = a.PARTY_ID

""")

result.show()

+--------+--------+--------+
|PARTY_ID|PARTY_ID|PARTY_ID|
+--------+--------+--------+
|      23|    null|      23|
|      25|      25|    null|
|      27|      27|      27|
|      29|      29|    null|
|      30|      30|      30|
|      32|      32|    null|
|      34|      34|      34|
|      52|    null|      52|
|      98|    null|      98|
+--------+--------+--------+

p86

- data CONDOCDECLAR;
- input DOCSDECLARATIONID CONTACTID;
- datalines;
- 12 34
- 13 67
- 87 90
- 65 56
- 45 56
- ;
- run;

- data crmcinfile;
- input WP_CINFULL $ CONTACTID;
- datalines;
- yes 34
- No 76
- No 80
- Yes 54
- Yes 56
- ;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *
data= [[12, 34],
       [13, 67],
       [87, 90],
       [65, 56],
       [45, 56]
       ]
columns=['DOCSDECLARATIONID','CONTACTID']      

spark = SparkSession.builder.appName('sas2py').getOrCreate()
CONDOCDECLAR=spark.createDataFrame(data=data,schema=columns)
CONDOCDECLAR.createOrReplaceTempView("CONDOCDECLAR")
CONDOCDECLAR.show()

data= [
       
       ["yes", 34],
       ["NO", 76],
       ["No", 80],
       ["yes", 54],
       ["Yes", 56]
       
       ]

columns=['WP_CINFULL', 'CONTACTID']      

spark = SparkSession.builder.appName('sas2py').getOrCreate()
crmcinfile=spark.createDataFrame(data=data,schema=columns)
crmcinfile.createOrReplaceTempView("crmcinfile")
crmcinfile.show()

+-----------------+---------+
|DOCSDECLARATIONID|CONTACTID|
+-----------------+---------+
|               12|       34|
|               13|       67|
|               87|       90|
|               65|       56|
|               45|       56|
+-----------------+---------+

+----------+---------+
|WP_CINFULL|CONTACTID|
+----------+---------+
|       yes|       34|
|        NO|       76|
|        No|       80|
|       yes|       54|
|       Yes|       56|
+----------+---------+

In [ ]:
result = spark.sql("""
select a.DOCSDECLARATIONID, a.CONTACTID, b.WP_CINFULL as newcinsfx from CONDOCDECLAR a left join crmcinfile b on a.CONTACTID = b.CONTACTID
""")

result.show()

+-----------------+---------+---------+
|DOCSDECLARATIONID|CONTACTID|newcinsfx|
+-----------------+---------+---------+
|               12|       34|      yes|
|               65|       56|      Yes|
|               45|       56|      Yes|
|               13|       67|     null|
|               87|       90|     null|
+-----------------+---------+---------+

p114

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [[23],
       [34],
       [45],
       [67],
       [78]]
      
columns=['onebank_id']      

spark = SparkSession.builder.appName('sas2py').getOrCreate()
output_refresh_date_c=spark.createDataFrame(data=data,schema=columns)
output_refresh_date_c.createOrReplaceTempView("output_refresh_date_c")
output_refresh_date_c.show()

data= [
       [23, 21, "Upendra"],
       [34, 67, "Ravi"],
       [55, 87, "Vishal"],
       [67, 54, "Anjali"],
       [87, 23, "Harsh"]
       ]
  
columns=['rm_1bank_id', 'lan_id', 'rm_full_name']
 
spark = SparkSession.builder.appName('sas2py').getOrCreate()
peoplesoft=spark.createDataFrame(data=data,schema=columns)
peoplesoft.createOrReplaceTempView("peoplesoft")
peoplesoft.show()

+----------+
|onebank_id|
+----------+
|        23|
|        34|
|        45|
|        67|
|        78|
+----------+

+-----------+------+------------+
|rm_1bank_id|lan_id|rm_full_name|
+-----------+------+------------+
|         23|    21|     Upendra|
|         34|    67|        Ravi|
|         55|    87|      Vishal|
|         67|    54|      Anjali|
|         87|    23|       Honey|
+-----------+------+------------+

In [ ]:
result = spark.sql("""

select a.* ,b.lan_id as lan_idsub ,b.rm_full_name as rm_full_name_sub from output_refresh_date_c as a left join peoplesoft as b on a.onebank_id=b.rm_1bank_id

""")

result.show()

+----------+---------+----------------+
|onebank_id|lan_idsub|rm_full_name_sub|
+----------+---------+----------------+
|        23|       21|         Upendra|
|        34|       67|            Ravi|
|        45|     null|            null|
|        67|       54|          Anjali|
|        78|     null|            null|
+----------+---------+----------------+

p72


- data all;
- input CIN_SFX $ f_ai $;
- datalines;
- Upe-ndra Y
- Shw-eta N
- Vis-hal Y
- So-nu Y
- Upe-ndra Y
- ;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [["Upe-ndra", "Y"],
       ["Shw-eta", "N"],
       ["Vis-hal", "Y"],
       ["So-nu", "Y"],
       ["Upe-ndra", "Y"]]
      
columns=['CIN_SFX', 'f_ai']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
all=spark.createDataFrame(data=data,schema=columns)
all.createOrReplaceTempView("all")
all.show()

+--------+----+
| CIN_SFX|f_ai|
+--------+----+
|Upe-ndra|   Y|
| Shw-eta|   N|
| Vis-hal|   Y|
|   So-nu|   Y|
|Upe-ndra|   Y|
+--------+----+

In [ ]:
from pyspark.sql.functions import regexp_replace

ai_clients_cin = spark.sql("""

select CIN_SFX, regexp_replace(CIN_SFX,'-', '') as newcinsfx_unmasked, count(distinct f_ai) as F_AI_Acct from all where f_ai='Y' group by 1

""")

ai_clients_cin.show()
ai_clients_cin.createOrReplaceTempView("ai_clients_cin")

+--------+------------------+---------+
| CIN_SFX|newcinsfx_unmasked|F_AI_Acct|
+--------+------------------+---------+
|Upe-ndra|           Upendra|        1|
| Vis-hal|            Vishal|        1|
|   So-nu|              Sonu|        1|
+--------+------------------+---------+

p30

- data t_avqpb_custmast_yyyymm;
- input BP_S_NUMBER $ CIN_SFX $;
- datalines;
- 12KUB Upen-dra
- 45TUC Kum-ar
- 35DUC Vish-al
- ;
- run;

- data datamart_yyyymm;
- input PARTY_ID newcinsfx $;
- datalines;
- 22 Upendra
- 66 HSBC
- 89 Kumar
- ;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [['12KUB', "Upen-dra"],
       ['45TUC', 'Kum-ar'],
       ["35DUC", 'Vish-al']
       ]
      
columns=['BP_S_NUMBER', 'CIN_SFX']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
t_avqpb_custmast_yyyymm=spark.createDataFrame(data=data,schema=columns)
t_avqpb_custmast_yyyymm.createOrReplaceTempView("t_avqpb_custmast_yyyymm")
t_avqpb_custmast_yyyymm.show()


data= [[22, "Upendra"],
       [66, "HSBC"],
       [89, "Kumar"]
       ]

columns=['PARTY_ID', 'newcinsfx']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
datamart_yyyymm=spark.createDataFrame(data=data,schema=columns)
datamart_yyyymm.createOrReplaceTempView("datamart_yyyymm")
datamart_yyyymm.show()

+-----------+--------+
|BP_S_NUMBER| CIN_SFX|
+-----------+--------+
|      12KUB|Upen-dra|
|      45TUC|  Kum-ar|
|      35DUC| Vish-al|
+-----------+--------+

+--------+---------+
|PARTY_ID|newcinsfx|
+--------+---------+
|      22|  Upendra|
|      66|     HSBC|
|      89|    Kumar|
+--------+---------+

In [ ]:
avaloq_eom = spark.sql("""

select a.BP_S_NUMBER, a.CIN_SFX, b.PARTY_ID from t_avqpb_custmast_yyyymm a inner join datamart_yyyymm b on b.newcinsfx = regexp_replace(a.CIN_SFX,'-', "")

""")

avaloq_eom.show()
avaloq_eom.createOrReplaceTempView("avaloq_eom")

+-----------+--------+--------+
|BP_S_NUMBER| CIN_SFX|PARTY_ID|
+-----------+--------+--------+
|      45TUC|  Kum-ar|      89|
|      12KUB|Upen-dra|      22|
+-----------+--------+--------+

p100


- data output;
- input name $ gender $ age aigrp $;
- datalines;
- Upendra M 25 Y
- Amit M 24 N
- Amruta F 26 Y
- Ram M 21 Y
- Sita F 20 N
- Gita F 27 Y
- ;
- run;


- proc freq data=&output.; 
- table aigrp; 
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [['Upendra', "M", 24, "Y"],
       ['Amit', 'M', 24, "N"],
       ["Amruta", "F", 26, "Y"],
       ["Ram", "M", 21, "Y"],
       ["Sita", "F", 20, "N"],
       ["Gita", "F", 27, "Y"]
       ]
      
columns=['name', 'gender', 'age', 'aigrp']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
output=spark.createDataFrame(data=data,schema=columns)
output.show()

+-------+------+---+-----+
|   name|gender|age|aigrp|
+-------+------+---+-----+
|Upendra|     M| 24|    Y|
|   Amit|     M| 24|    N|
| Amruta|     F| 26|    Y|
|    Ram|     M| 21|    Y|
|   Sita|     F| 20|    N|
|   Gita|     F| 27|    Y|
+-------+------+---+-----+

In [ ]:
import sys
import pyspark.sql.functions as F
from pyspark.sql import Window
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

result = output.groupBy('aigrp').agg(F.count('aigrp').alias('Frequency')).selectExpr('*','100 * Frequency / sum(Frequency) over() Percent')
result = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
result = result.withColumn('Cumulative_Percentage', F.sum(result.Percent).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))

result.show()

+-----+---------+------------------+--------------------+---------------------+
|aigrp|Frequency|           Percent|Cumulative_Frequency|Cumulative_Percentage|
+-----+---------+------------------+--------------------+---------------------+
|    Y|        4| 66.66666666666667|                   4|    66.66666666666667|
|    N|        2|33.333333333333336|                   6|                100.0|
+-----+---------+------------------+--------------------+---------------------+

In [ ]:
import pyspark.sql.functions as F
from pyspark.sql import Window

def proc_freq(data):
  result = data.groupBy('aigrp').agg(F.count('aigrp').alias('Frequency')).selectExpr('*','100 * Frequency / sum(Frequency) over() Percent')
  result = result.withColumn('Cumulative_Frequency', F.sum(result.Frequency).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
  result = result.withColumn('Cumulative_Percentage', F.sum(result.Percent).over(Window.partitionBy().orderBy().rowsBetween(-sys.maxsize,0)))
  return result

freq_aigrp = proc_freq(data=output)
freq_aigrp.show()

+-----+---------+------------------+--------------------+---------------------+
|aigrp|Frequency|           Percent|Cumulative_Frequency|Cumulative_Percentage|
+-----+---------+------------------+--------------------+---------------------+
|    Y|        4| 66.66666666666667|                   4|    66.66666666666667|
|    N|        2|33.333333333333336|                   6|                100.0|
+-----+---------+------------------+--------------------+---------------------+

p128

- data BIP_SYN_VB2T002_PRODUCT;
- input product_id product_name product_desc PRODUCT_DESC_LVL1 EFFECTIVE_TO_DATE;
- datalines;
- 23 Laptop Electronic ELecLevel1 12Dec2022
- 73 Mobile SemiElectronic SemiElecLevel2 25Dec2022
- 18 Computer Electronic ElecLevel2 23Dec2022
- 5 Mixer HardCordElectronic HardElecLevel6 12Jan2023
- 14 Juicer SemiHardElectronic SemiHardLevel7 26Jan2021
- ;
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [
       [23, 'Laptop', 'Electronic', 'ELecLevel1', '12Dec2022'],
       [73, "Mobile", "SemiElectronic", 'SemiElecLevel2', '25Dec2022'],
       [18, 'Computer', 'Electronic', 'ElecLevel2', '23Dec2022'],
       [5, 'Mixer', 'HardCordElectronic', 'HardElecLevel6', '12Jan2023'],
       [14, 'Juicer', 'SemiHardElectronic', 'SemiHardLevel7', '26Jan2021']
       ]

columns=['product_id', 'product_name', 'product_desc', 'PRODUCT_DESC_LVL1', 'EFFECTIVE_TO_DATE']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
BIP_SYN_VB2T002_PRODUCT=spark.createDataFrame(data=data,schema=columns)
BIP_SYN_VB2T002_PRODUCT.show()

+----------+------------+------------------+-----------------+-----------------+
|product_id|product_name|      product_desc|PRODUCT_DESC_LVL1|EFFECTIVE_TO_DATE|
+----------+------------+------------------+-----------------+-----------------+
|        23|      Laptop|        Electronic|       ELecLevel1|        12Dec2022|
|        73|      Mobile|    SemiElectronic|   SemiElecLevel2|        25Dec2022|
|        18|    Computer|        Electronic|       ElecLevel2|        23Dec2022|
|         5|       Mixer|HardCordElectronic|   HardElecLevel6|        12Jan2023|
|        14|      Juicer|SemiHardElectronic|   SemiHardLevel7|        26Jan2021|
+----------+------------+------------------+-----------------+-----------------+

In [ ]:
def proc_sort(data):
  df = data.select('product_id', 'product_name', 'product_desc', 'PRODUCT_DESC_LVL1', 'EFFECTIVE_TO_DATE')
  result = df.orderBy(col("product_id").asc(),col("EFFECTIVE_TO_DATE").desc())
  return result

product = proc_sort(data=BIP_SYN_VB2T002_PRODUCT)
product.show()

+----------+------------+------------------+-----------------+-----------------+
|product_id|product_name|      product_desc|PRODUCT_DESC_LVL1|EFFECTIVE_TO_DATE|
+----------+------------+------------------+-----------------+-----------------+
|         5|       Mixer|HardCordElectronic|   HardElecLevel6|        12Jan2023|
|        14|      Juicer|SemiHardElectronic|   SemiHardLevel7|        26Jan2021|
|        18|    Computer|        Electronic|       ElecLevel2|        23Dec2022|
|        23|      Laptop|        Electronic|       ELecLevel1|        12Dec2022|
|        73|      Mobile|    SemiElectronic|   SemiElecLevel2|        25Dec2022|
+----------+------------+------------------+-----------------+-----------------+

p212

- data dpm2;
- input bp_s_number start_dt $ open_date $;
- datalines;
- 43 12Jan2022 16Jan2022
- 62 18Jan2022 20Jan2022
- 20 20Feb2022 28Feb2022
- 78 13Mar2022 19Mar2022
- 55 20Mar2022 25Mar2022
- ;
- run;


- proc sort data = dpm2; 
- by bp_s_number descending start_dt open_date; 
- run;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [
       [43, '12Jan2022', '16Jan2022'],
       [62, '18Jan2022', '20Jan2022'],
       [20, '20Feb2022', '28Feb2022'],
       [78, '13Mar2022', '19Mar2022'],
       [55, '20Mar2022', '25Mar2022']
       ]
columns=['bp_s_number', 'start_dt', 'opendate']

spark = SparkSession.builder.appName('sas2py').getOrCreate()
dpm2=spark.createDataFrame(data=data,schema=columns)
dpm2.show()

+-----------+---------+---------+
|bp_s_number| start_dt| opendate|
+-----------+---------+---------+
|         43|12Jan2022|16Jan2022|
|         62|18Jan2022|20Jan2022|
|         20|20Feb2022|28Feb2022|
|         78|13Mar2022|19Mar2022|
|         55|20Mar2022|25Mar2022|
+-----------+---------+---------+

In [ ]:
def proc_sort(data):

  result = data.sort("bp_s_number","start_dt", "opendate")
  return result

result = proc_sort(data=dpm2)
result.show()

+-----------+---------+---------+
|bp_s_number| start_dt| opendate|
+-----------+---------+---------+
|         20|20Feb2022|28Feb2022|
|         43|12Jan2022|16Jan2022|
|         55|20Mar2022|25Mar2022|
|         62|18Jan2022|20Jan2022|
|         78|13Mar2022|19Mar2022|
+-----------+---------+---------+

In [ ]:
dpm2.sort("bp_s_number","start_dt", "opendate").show(truncate=False)

+-----------+---------+---------+
|bp_s_number|start_dt |opendate |
+-----------+---------+---------+
|20         |20Feb2022|28Feb2022|
|43         |12Jan2022|16Jan2022|
|55         |20Mar2022|25Mar2022|
|62         |18Jan2022|20Jan2022|
|78         |13Mar2022|19Mar2022|
+-----------+---------+---------+

p198

- data snapshot_dvc;
- input rm_1bank_id pc_code_name;
- datalines;
- 12 TRMs@Branch
- 16 TRMs@Branch
- 18 DLTRMs@Bankcv
- 12 codeTRMs@Branchmn
- 12 codeTRMs@Branchbn
- ;
- run;

- proc sql;
- create table rm_grpb as
- select distinct rm_1bank_id
from snapshot_dvc where pc_code_name contains 'TRMs@Branch';
- quit;

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [
       [12, "TRMs@Branch"],
       [16, "TRMs@Branch"],
       [20, "TRMs@Branch"],
       [82, "TRMs@Crunch"],
       [26, "TRMs@code"]
       ]

columns=["rm_1bank_id", "pc_code_name"]

spark = SparkSession.builder.appName('sas2py').getOrCreate()
snapshot_dvc=spark.createDataFrame(data=data,schema=columns)
snapshot_dvc.createOrReplaceTempView("snapshot_dvc")
snapshot_dvc.show()

+-----------+------------+
|rm_1bank_id|pc_code_name|
+-----------+------------+
|         12| TRMs@Branch|
|         16| TRMs@Branch|
|         20| TRMs@Branch|
|         82| TRMs@Crunch|
|         26|   TRMs@code|
+-----------+------------+

In [ ]:
rm_grpb = spark.sql("""select distinct(rm_1bank_id) from snapshot_dvc where pc_code_name like '%TRMs@Branch%'""")
rm_grpb.createOrReplaceTempView("rm_grpb")
rm_grpb.show()

+-----------+
|rm_1bank_id|
+-----------+
|         12|
|         16|
|         20|
+-----------+

p226

In [ ]:
import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.functions  import *

data= [
       ["Upen-dra"],
       ["Am-it"],
       ["Ku-mar"],
       ["HS-BC"],
       ["Ku-nal"]
       ]

columns=["cin_sfx"]

spark = SparkSession.builder.appName('sas2py').getOrCreate()
barbell=spark.createDataFrame(data=data,schema=columns)
barbell.createOrReplaceTempView("barbell")
barbell.show()

+--------+
| cin_sfx|
+--------+
|Upen-dra|
|   Am-it|
|  Ku-mar|
|   HS-BC|
|  Ku-nal|
+--------+

In [ ]:
from pyspark.sql.functions import regexp_replace
barbell_list = spark.sql("""
select distinct trim(regexp_replace(cin_sfx,"-","")) as newcinsfx from barbell
""")
barbell_list.createOrReplaceTempView("barbell_list")
barbell_list.show()

+---------+
|newcinsfx|
+---------+
|     Amit|
|  Upendra|
|    Kunal|
|    Kumar|
|     HSBC|
+---------+

In [ ]:
TR_ENTITYMART = "cvy"

In [ ]:
 print(f"""NOTE: TR_ENTITYMART={TR_ENTITYMART} """)

NOTE: TR_ENTITYMART=cvy